sonic-net/sonic-pins

- p4rt_app/BUILD.bazel
libswsscommon is actually linked statically, so not
technically a dependency, but it is installed anyway
by the build system so there's no harm either.
libswsscommon pulls in transitive libraries we do need:
libhiredis, libnl*, libc, libgcc, libstdc++
libgmpxx4ldbl required for p4_symbolic
> Add depends to p4rt debian package

- install_dependencies.sh
sonic-swss-common lib will add dependency to libyang soon, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.
> Install libyang to azure pipeline

- p4rt_app/p4rt.cc
This should also be covered by the startup scripts, but removing it here in case other environments act differently.
> Default to no socket connection.

- install_dependencies.sh
- p4rt_app/p4runtime/p4info_verification_schema.cc
- p4rt_app/p4runtime/p4info_verification_schema_test.cc
- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/sonic/app_db_acl_def_table_manager.cc
- p4rt_app/sonic/app_db_manager.cc
- p4rt_app/sonic/app_db_manager.h
- p4rt_app/utils/table_utility.cc
- p4rt_app/utils/table_utility.h
- p4rt_app/utils/table_utility_test.cc
- pins_infra_deps.bzl
High Level Design: https://github.com/sonic-net/SONiC/pull/1088
This PR is for changes in sonic-pins repo
This changes include,
- ConfigureAppDbTables() to create and publish Table definitions for all extension tables. Validate response for the success, if failed return failure back to P4RT client
- A function to insert table definition in json format
- A function to publish tables definition set into AppDb
- New table types kTblsDefinitionSet and kExt, modified existing type kDefinition to kAclDefinition
- Add/update table utility functions around new and modified table types
- Add list of fixed table definitions, rest any other table definition is considered of EXT type
Not covered in this commit,
- meter
- CRM
- batching
Signed-off-by: svshah-intel …
> PINS Extension tables support

- install_dependencies.sh
- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/sonic/app_db_acl_def_table_manager.cc
- p4rt_app/sonic/app_db_acl_def_table_manager_test.cc
- p4rt_app/sonic/app_db_manager.cc
- p4rt_app/sonic/app_db_manager.h
- p4rt_app/sonic/app_db_to_pdpi_ir_translator.cc
- p4rt_app/sonic/hashing.cc
- p4rt_app/tests/p4_programs_test.cc
This header file comes from an external package, and a very old version of the header file has been checked into swss-common. This will cause problems for the upcoming Bookworm upgrade.
Change references to the header file to use the Debian package nlohmann-json-dev (added in sonic-net/sonic-buildimage#16308), instead of from swss-common.
> Use json.hpp from nlohmann-json-dev instead of from swss-common

- p4_pdpi/packetlib/BUILD.bazel
- p4_pdpi/packetlib/bit_widths.h
- p4_pdpi/packetlib/packetlib.cc
- p4_pdpi/packetlib/packetlib.h
- p4_pdpi/packetlib/packetlib.proto
- p4_pdpi/packetlib/packetlib_fuzzer_test.cc
- p4_pdpi/packetlib/packetlib_test_runner.cc
- p4_pdpi/packetlib/packetlib_test_runner.expected
- p4_pdpi/packetlib/packetlib_unit_test.cc
PR Description :
[packetlib] Add SAI P4 BMv2 packet_in header support in packetlib.
Build Results :
2024/05/13 11:58:31 Downloading https://releases.bazel.build/4.2.0/release/bazel-4.2.0-linux-x86_64...
Downloading: 48 MB out of 48 MB (100%) 
Extracting Bazel installation...
INFO: Elapsed time: 1934.877s, Critical Path: 36.37s
INFO: 5254 processes: 818 internal, 4436 linux-sandbox.
INFO: Build completed successfully, 5254 total actions
bibhuprasad@eaba4ee0062c:/sonic/src/sonic-p4rt/sonic-pins$ 
INFO: Analyzed 100 targets (18 packages …
> [packetlib] Add SAI P4 BMv2 packet_in header support in packetlib.

- gutil/BUILD.bazel
- gutil/version.cc
- gutil/version.h
- p4_pdpi/BUILD.bazel
- p4_pdpi/p4_runtime_session.cc
- p4_pdpi/p4_runtime_session.h
PR Description : 
[PDPI] Add convenience functions to P4 Runtime Session.
Build Results :
ibhuprasad@eaba4ee0062c:/sonic/src/sonic-p4rt/sonic-pins$ 
INFO: Analyzed 74 targets (2 packages loaded, 122 targets configured).
INFO: Found 74 targets...
INFO: Elapsed time: 6.428s, Critical Path: 4.97s
INFO: 8 processes: 1 internal, 7 linux-sandbox.
INFO: Build completed successfully, 8 total actions
INFO: Analyzed 100 targets (1 packages loaded, 122 targets configured).
INFO: Found 100 targets...
INFO: Elapsed time: 81.049s, Critical Path: 25.87s
INFO: 83 processes: 42 internal, 41 linux-sandbox. …
> [PDPI] Add convenience functions to P4 Runtime Session.

- p4_pdpi/ir.cc
- p4_pdpi/ir.h
- p4_pdpi/ir.proto
- p4_pdpi/p4_runtime_session_extras.cc
- p4_pdpi/p4_runtime_session_extras.h
- p4_pdpi/pd.cc
- p4_pdpi/pd.h
- p4_pdpi/testing/table_entry_gunit_test.cc
[PDPI] Transition numerous functions to use a proto IrTableEntries instead of a vector.
INFO: Analyzed 74 targets (0 packages loaded, 0 targets configured).
INFO: Found 74 targets...
INFO: Elapsed time: 67.244s, Critical Path: 12.61s
INFO: 55 processes: 4 internal, 51 linux-sandbox.
INFO: Build completed successfully, 55 total actions
bibhuprasad@eaba4ee0062c:/sonic/src/sonic-p4rt/sonic-pins$ 
INFO: Analyzed 100 targets (0 packages loaded, 0 targets configured).
INFO: Found 100 targets...
INFO: Elapsed time: 196.281s, Critical Path: 29.62s
INFO: 107 processes: 2 internal, 105 …
> [PDPI] Transition numerous functions to use a proto IrTableEntries instead of a vector.

- p4_pdpi/BUILD.bazel
- p4_pdpi/p4_runtime_session_extras.cc
- p4_pdpi/p4_runtime_session_extras.h
- p4_pdpi/p4_runtime_session_extras.proto
[p4rt-session] Add convenience functions for installing entities.
INFO: Analyzed 76 targets (1 packages loaded, 71 targets configured).
INFO: Found 76 targets...
INFO: Elapsed time: 4.356s, Critical Path: 3.71s
INFO: 11 processes: 3 internal, 8 linux-sandbox.
INFO: Build completed successfully, 11 total actions
INFO: Analyzed 100 targets (1 packages loaded, 107 targets configured).
INFO: Found 100 targets...
INFO: Elapsed time: 1.107s, Critical Path: 0.02s …
> [p4rt-session] Add convenience functions for installing entities.

- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/sonic/response_handler.cc
- p4rt_app/sonic/response_handler_test.cc
- p4rt_app/tests/response_path_test.cc
- pins_infra_deps.bzl
Use a canonical key when updating the read cache. Map SWSS_RC_NOT_EXECUTED to ABORTED in p4rt.
rkavitha@0c0d9cfbd72e:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 233 targets (4 packages loaded, 511 targets configured).
INFO: Found 233 targets...
INFO: Elapsed time: 32.502s, Critical Path: 29.76s
INFO: 36 processes: 4 internal, 32 linux-sandbox.
INFO: Build completed successfully, 36 total actions
rkavitha@0c0d9cfbd72e:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS ...
INFO: Analyzed 233 targets (0 packages loaded, 0 targets configured).
INFO: Found 151 targets and 82 test targets...
INFO: Elapsed time: 19.595s, Critical Path: 4.97s
INFO: 23 processes: 1 internal, 8 linux-sandbox, 14 local.
INFO: Build completed successfully, 23 total …
> Use a canonical key when updating the read cache. Map SWSS_RC_NOT_EXECUTED to ABORTED in p4rt.

- p4_pdpi/ir_tools_test.cc
- p4_pdpi/testing/sequencing_test_runner.cc
- p4_pdpi/testing/testdata/info.expected
- p4_pdpi/testing/testdata/main.p4
- p4_pdpi/testing/testdata/main_p4_pd.expected
- p4_pdpi/testing/testdata/sequencing.expected
Refactor the test P4 program with tables and actions that make more sense with reference annotation.
INFO: Analyzed 76 targets (6 packages loaded, 447 targets configured).
INFO: Found 76 targets...
INFO: Elapsed time: 26.937s, Critical Path: 7.40s
INFO: 39 processes: 7 internal, 32 linux-sandbox.
INFO: Build completed successfully, 39 total actions
INFO: Analyzed 102 targets (18 packages loaded, 487 targets configured).
INFO: Found 102 targets...
INFO: Elapsed time: 1.108s, Critical Path: 0.03s …
> Refactor the test P4 program with tables and actions that make more sense with reference annotation.

- p4_pdpi/BUILD.bazel
- p4_pdpi/sequencing_util.cc
- p4_pdpi/sequencing_util.h
- p4_pdpi/testing/BUILD.bazel
- p4_pdpi/testing/sequencing_util_test_runner.cc
- p4_pdpi/testing/testdata/sequencing_util.expected
[P4 Reachability analysis] Creates a helper function to create ReferredTableEntries for an entry that refers to other entries.
bibhuprasad@eaba4ee0062c:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 245 targets (3 packages loaded, 196 targets configured).
INFO: Found 245 targets...
INFO: Elapsed time: 16.425s, Critical Path: 9.45s
INFO: 20 processes: 13 internal, 7 linux-sandbox.
INFO: Build completed successfully, 20 total actions
bibhuprasad@eaba4ee0062c:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS p4_pdpi/...
INFO: Analyzed 80 targets (0 packages loaded, 0 targets configured).
INFO: Found 46 targets and 34 test targets...
INFO: Elapsed time: 1.518s, Critical Path: 0.55s
INFO: 4 processes: 5 linux-sandbox. …
> [P4 Reachability analysis] Creates a helper function to create ReferredTableEntries for an entry that refers to other entries.

- p4_pdpi/ir.cc
- p4_pdpi/ir.proto
- p4_pdpi/pd.cc
- p4_pdpi/testing/testdata/info.expected
- p4_pdpi/utils/ir.cc
- p4_pdpi/utils/ir.h
- p4_pdpi/utils/ir_test.cc
PR Description :
[IrP4Info] Extend table/action/match definitions with is_unsupported field.
Build Results :
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 257 targets (0 packages loaded, 0 targets configured).
INFO: Found 257 targets...
INFO: Elapsed time: 308.953s, Critical Path: 30.87s
INFO: 216 processes: 14 internal, 202 linux-sandbox.
INFO: Build completed successfully, 216 total actions
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ 
UT Results :
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS p4_pdpi/...
INFO: Analyzed 84 targets (0 packages loaded, 0 targets configured).
INFO: Found 48 targets and 36 test targets...
INFO: Elapsed time: 1.753s, Critical Path: 0.37s …
> [IrP4Info] Extend table/action/match definitions with is_unsupported field.

- p4_pdpi/pd.cc
- p4_pdpi/testing/testdata/table_entry.expected
[PDPI] Fix roundtrip bugs in color counter translation.
bibhuprasad@eonms7vm1:~/Sonic_04_29_2024/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Google/tools/keyword_checks.sh .
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 266 targets (0 packages loaded, 0 targets configured).
INFO: Found 266 targets...
INFO: Elapsed time: 0.712s, Critical Path: 0.00s
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS ...
INFO: Analyzed 266 targets (0 packages loaded, 0 targets configured).
INFO: Found 170 targets and 96 test targets...
INFO: Elapsed time: 1.993s, Critical Path: 0.54s
INFO: 14 processes: 18 …
> [PDPI] Fix roundtrip bugs in color counter translation.

- p4_symbolic/bmv2/expected/basic.pb.txt
- p4_symbolic/bmv2/expected/hardcoded.pb.txt
- p4_symbolic/bmv2/expected/reflector.pb.txt
- p4_symbolic/bmv2/expected/table.pb.txt
**Build and Test:**
rkavitha@148ad99dcce3:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 266 targets (0 packages loaded, 0 targets configured).
INFO: Found 266 targets...
INFO: Elapsed time: 0.497s, Critical Path: 0.00s
rkavitha@148ad99dcce3:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS ...
INFO: Analyzed 266 targets (0 packages loaded, 0 targets configured).
INFO: Found 170 targets and 96 test targets...
INFO: Elapsed time: 0.540s, Critical Path: 0.01s
//gutil:collections_test                                        (cached) PASSED in 1.3s
//gutil:io_test …
> Initial import of p4-symbolic - bmv2

- p4rt_app/p4runtime/BUILD.bazel
- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/p4runtime/p4runtime_read.cc
- p4rt_app/p4runtime/p4runtime_read.h
divya@1ce2fff47237:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 271 targets (0 packages loaded, 0 targets configured).
INFO: Found 271 targets...
...
INFO: Elapsed time: 318.048s, Critical Path: 149.70s
INFO: 203 processes: 94 internal, 109 linux-sandbox.
INFO: Build completed successfully, 203 total actions
divya@1ce2fff47237:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS ...
INFO: Analyzed 271 targets (0 packages loaded, 0 targets configured).
INFO: Found 172 targets and 99 test targets...
INFO: Elapsed time: 29.591s, Critical Path: 5.20s
INFO: 30 processes: 1 internal, 13 linux-sandbox, 16 local.
INFO: Build completed successfully, 30 total actions
//gutil:collections_test                                        (cached) PASSED in …
> Factor out the read path code from p4runtime_impl.cc

- gutil/status_matchers.h
- p4rt_app/p4runtime/BUILD.bazel
- p4rt_app/p4runtime/p4info_verification.cc
- p4rt_app/p4runtime/p4info_verification_test.cc
- p4rt_app/p4runtime/p4runtime_impl.cc
[P4RT App] Tolerate P4Infos with @unsupported tables/actions/match fields.
Keyword check:
Build Results:
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analyzed 281 targets (0 packages loaded, 17436 targets configured).
INFO: Found 281 targets...
INFO: Elapsed time: 8.601s, Critical Path: 4.80s
INFO: 3 processes: 1 internal, 2 linux-sandbox.
INFO: Build completed successfully, 3 total actions
UT Results: …
> [P4RT App] Tolerate P4Infos with @unsupported tables/actions/match fields.

- sai_p4/instantiations/google/sai_pd.proto
Fix build issue in SAI P4
**Build and UT:**
rkavitha@71e20596914c:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analyzed 284 targets (0 packages loaded, 17440 targets configured).
INFO: Found 284 targets...
INFO: Elapsed time: 7.792s, Critical Path: 0.31s
rkavitha@71e20596914c:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analyzed 284 targets (0 packages loaded, 17440 targets configured).
INFO: Found 180 targets and 104 test targets...
INFO: Elapsed time: 74.086s, Critical …
> Fix build issue in SAI P4

- p4rt_app/scripts/p4rt_route_measurement_test.cc
INFO: Analyzed 289 targets (0 packages loaded, 23 targets configured).
INFO: Found 289 targets...
INFO: Elapsed time: 0.976s, Critical Path: 0.02s
INFO: Analyzed 289 targets (0 packages loaded, 0 targets configured).
INFO: Found 183 targets and 106 test targets...
INFO: Elapsed time: 61.135s, Critical Path: 21.21s
INFO: 111 processes: 119 linux-sandbox, 16 local.
INFO: Build completed successfully, 111 …
> [P4RT]: P4RT build failure

- p4_pdpi/ir_tools_test.cc
- p4_pdpi/p4_runtime_session_extras.cc
- p4_pdpi/pd.cc
- p4_pdpi/pd.h
- p4_pdpi/testing/sequencing_test_runner.cc
- p4_pdpi/testing/sequencing_util_test_runner.cc
- p4_pdpi/testing/table_entry_gunit_test.cc
- p4_pdpi/testing/table_entry_test_runner.cc
- sai_p4/instantiations/google/test_tools/test_entries.cc
[pd][multicast] Rename PD->IR/PI to set up for deprecation.
Keyword Check:
Build Results:
INFO: Analyzed 284 targets (0 packages loaded, 0 targets configured).
INFO: Found 284 targets...
INFO: Elapsed time: 0.866s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 284 targets (0 packages loaded, 91 targets configured).
INFO: Found 180 targets and 104 test …
> [Comb][multicast] Rename PD->IR/PI to set up for deprecation.

- p4rt_app/sonic/BUILD.bazel
- p4rt_app/sonic/app_db_manager.cc
- p4rt_app/sonic/app_db_manager_test.cc
- p4rt_app/sonic/app_db_to_pdpi_ir_translator.cc
- p4rt_app/sonic/app_db_to_pdpi_ir_translator.h
- p4rt_app/sonic/app_db_to_pdpi_ir_translator_test.cc
- p4rt_app/sonic/packet_replication_entry_translation.cc
- p4rt_app/sonic/packet_replication_entry_translation.h
- p4rt_app/sonic/packet_replication_entry_translation_test.cc
- p4rt_app/sonic/redis_connections.h
INFO: Analyzed 286 targets (0 packages loaded, 37 targets configured).
INFO: Found 286 targets...
...
45 | absl::StatusOr<mpz_class> ParseInteger(const std::string& int_str) {
|                           ^~~~~~~~~~~~
INFO: Elapsed time: 256.208s, Critical Path: 59.17s
INFO: 1100 processes: 601 internal, 499 linux-sandbox.
INFO: Build completed successfully, 1100 total actions
INFO: Analyzed 286 targets (2 packages loaded, 127 targets configured).
INFO: Found 181 targets and 105 …
> [P4RT]: Add APP DB translation for PacketReplicationEntries

- p4_pdpi/packetlib/packetlib.cc
p4_pdpi build failure fix.
Keyword Check:
Build Results:
INFO: Analyzed 307 targets (0 packages loaded, 0 targets configured).
INFO: Found 307 targets...
INFO: Elapsed time: 0.833s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 307 targets (0 packages loaded, 0 targets configured).
INFO: Found 193 …
> [P4-PDPI] Fix p4_pdpi build failure.

- lib/gnmi/BUILD.bazel
- lib/gnmi/openconfig.proto
Adding openconfig.proto to gnmi lib.
Keyword Check:
Build Results:
INFO: Analyzed 322 targets (0 packages loaded, 0 targets configured).
INFO: Found 322 targets...
INFO: Elapsed time: 1.149s, Critical Path: 0.01s
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins
UT Results:
INFO: Analyzed 322 targets (1 packages loaded, 3 targets configured).
INFO: Found …
> [Thinkit]Adding openconfig.proto to gnmi lib.

- lib/gnmi/BUILD.bazel
- lib/gnmi/openconfig.proto
- tests/lib/switch_test_setup_helpers.cc
Adding switch_test_setup_helpers.cc to lib tests.
Keyword Check:
bibhuprasad@eonms7vm1:~/Sonic_06_06_2024/sonic-buildimage/src/sonic-p4rt/sonic-pins/tests/lib$ ~/keyword_checks.sh .
Build Results:
INFO: Analyzed 322 targets (0 packages loaded, 0 targets configured).
INFO: Found 322 targets...
INFO: Elapsed time: 0.661s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 322 targets (0 packages loaded, 0 targets …
> [Thinkit]Adding switch_test_setup_helpers.cc to lib tests.

- lib/p4rt/BUILD.bazel
- lib/p4rt/p4rt_port.cc
- lib/p4rt/p4rt_port.h
[P4rtPortIds] Add functions to construct vectors of P4rtPortIds from spans.
Keyword Check:
Build Results:
INFO: Analyzed 323 targets (2 packages loaded, 63 targets configured).
INFO: Found 323 targets...
INFO: Elapsed time: 0.910s, Critical Path: 0.01s
UT Results:
INFO: Analyzed 323 targets (0 packages …
> [Thinkit][P4rtPortIds] Add functions to construct vectors of P4rtPortIds from spans.

- lib/validator/BUILD.bazel
- lib/validator/common_backend.cc
- lib/validator/common_backend.h
- lib/validator/validator.cc
- lib/validator/validator.h
- lib/validator/validator_backend.cc
- lib/validator/validator_backend.h
- lib/validator/validator_backend_test.cc
Added CommonBackend for GPINs validator.
Add initial implementation of Validator and ValidatorBackend.
Keyword Check:
Build Results:
INFO: Analyzed 332 targets (1 packages loaded, 11 targets configured).
INFO: Found 332 targets...
INFO: Elapsed time: 2.534s, Critical Path: 1.56s
INFO: 7 processes: 1 internal, 6 linux-sandbox.
INFO: Build completed successfully, 7 total actions
UT Results:
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS …
> [Thinkit] Added CommonBackend for GPINs validator. Add initial implementation of Validator and ValidatorBackend.

- dvaas/packet_injection.cc
- dvaas/packet_injection.h
- dvaas/test_run_validation.cc
- dvaas/test_run_validation.h
- dvaas/test_vector.proto
INFO: Analyzed 332 targets (0 packages loaded, 0 targets configured).
INFO: Found 332 targets...
...
INFO: Elapsed time: 10.796s, Critical Path: 7.87s
INFO: 16 processes: 1 internal, 15 linux-sandbox.
INFO: Build completed successfully, 16 total actions
INFO: Analyzed 331 targets (0 packages loaded, 269 targets configured).
INFO: Found 216 targets and 115 test targets...
INFO: Elapsed time: 71.695s, Critical Path: 16.10s
INFO: 120 processes: 127 linux-sandbox, 17 local.
INFO: Build …
> [Dvaas] Updating packet_injection and test_run_validation files.

- lib/validator/BUILD.bazel
- lib/validator/pins_backend.cc
- lib/validator/pins_backend.h
- lib/validator/validator_backend.h
Added PINSBackend for GPINs validator.
Keyword Check:
Build Results:
INFO: Analyzed 333 targets (0 packages loaded, 0 targets configured).
INFO: Found 333 targets...
INFO: Elapsed time: 0.531s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 333 targets (0 packages loaded, 0 targets configured).
INFO: …
> [Thinkit] Added PINSBackend for GPINs validator.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- tests/BUILD.bazel
- tests/thinkit_gnmi_subscribe_tests.cc
- tests/thinkit_gnmi_subscribe_tests.h
- tests/thinkit_util.h
gNMI Subscribe sanity test
Keyword Check:
Build Results:
INFO: Analyzed 338 targets (0 packages loaded, 0 targets configured).
INFO: Found 338 targets...
INFO: Elapsed time: 0.587s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 338 targets (0 packages loaded, 0 targets configured).
INFO: Found 222 …
> [Comb] gNMI Subscribe sanity test

- thinkit/BUILD.bazel
- thinkit/packet_generation_finalizer.h
Adding packet_generation_finalizer.h to thinkit
Keyword Check:
Build Results:
INFO: Analyzed 342 targets (0 packages loaded, 0 targets configured).
INFO: Found 342 targets...
INFO: Elapsed time: 0.975s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 342 targets (0 packages loaded, 107 targets …
> [Thinkit] Adding packet_generation_finalizer.h to thinkit

- tests/BUILD.bazel
- tests/thinkit_sanity_tests.cc
- tests/thinkit_sanity_tests.h
INFO: Analyzed 348 targets (1 packages loaded, 7 targets configured).
INFO: Found 348 targets...
INFO: Elapsed time: 0.431s, Critical Path: 0.00s
INFO: Analyzed 348 targets (0 packages loaded, 275 targets configured).
INFO: Found 227 targets and 121 test targets...
INFO: Elapsed time: 73.093s, Critical Path: 22.44s
INFO: 126 processes: 133 linux-sandbox, 17 local.
INFO: Build completed successfully, 126 total actions
//gutil:collections_test                                                 PASSED in 0.5s …
> [Thinkit] gnmi set mtu test,  Skip Interface checks for 10G SFP+ ports &  Remove interface port-speed checks.

- tests/BUILD.bazel
- tests/thinkit_gnmi_interface_tests.cc
- tests/thinkit_gnmi_interface_tests.h
- tests/thinkit_sanity_tests.cc
INFO: Analyzed 349 targets (0 packages loaded, 0 targets configured).
INFO: Found 349 targets...
INFO: Elapsed time: 13.656s, Critical Path: 9.18s
INFO: 12 processes: 1 internal, 11 linux-sandbox.
INFO: Build completed successfully, 12 total actions
INFO: Analyzed 349 targets (0 packages loaded, 0 targets configured).
INFO: Found 228 targets and 121 test targets...
INFO: Elapsed time: 63.435s, Critical Path: 16.43s
INFO: 126 processes: 133 linux-sandbox, 17 local.
INFO: Build completed successfully, 126 total actions
//gutil:collections_test                                                 PASSED …
> [Thinkit] gNMI set admin-status test

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/validator/BUILD.bazel
- lib/validator/pins_backend.cc
- lib/validator/pins_backend.h
- lib/validator/validator.cc
Call validation backends setup from the validator.Added port up validator to pins backend.
Keyword Check:
Build Results:
INFO: Analyzed 352 targets (25 packages loaded, 349 targets configured).
INFO: Found 352 targets...
INFO: Elapsed time: 1.593s, Critical Path: 0.01s
UT Results:
INFO: Analyzed 352 …
> [Thinkit] Call validation backends setup from the validator.Added port up validator to pins backend.

- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
- thinkit/BUILD.bazel
- thinkit/bazel_test_environment.cc
- thinkit/bazel_test_environment.h
- thinkit/bazel_test_environment_test.cc
Fixing helper function to take care of OC paths containing values in [1/1] format. Implement portable Bazel test environment.
Keyword Check:
Build Results:
INFO: Analyzed 355 targets (0 packages loaded, 0 targets configured).
INFO: Found 355 targets...
INFO: Elapsed time: 0.492s, Critical Path: 0.00s
UT Results:
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS …
> [Comb] Fixing helper function to take care of OC paths containing values in [1/1] format. Implement portable Bazel test environment.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/validator/BUILD.bazel
- lib/validator/common_backend.cc
- lib/validator/pins_backend.cc
- lib/validator/pins_backend.h
- lib/validator/validator_lib.cc
- lib/validator/validator_lib.h
Moved validator to free functions
Keyword Check:
Build Results:
INFO: Analyzed 358 targets (0 packages loaded, 0 targets configured).
INFO: Found 358 targets...
INFO: Elapsed time: 0.625s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 358 targets (0 packages loaded, 0 targets configured).
INFO: Found …
> [Thinkit] Moved validator to free functions

- thinkit/BUILD.bazel
- thinkit/bazel_test_environment.h
- thinkit/generic_testbed.h
- thinkit/generic_testbed_fixture.h
- thinkit/mock_control_interface.h
- thinkit/mock_control_interface_test.cc
- thinkit/mock_generic_testbed.h
- thinkit/mock_generic_testbed_test.cc
- thinkit/mock_ssh_client.h
- thinkit/proto/BUILD.bazel
- thinkit/proto/generic_testbed.proto
- thinkit/ssh_client.h
- thinkit/test_environment.h
INFO: Analyzed 366 targets (1 packages loaded, 66 targets configured).
INFO: Found 366 targets...
INFO: Elapsed time: 8.388s, Critical Path: 7.24s
INFO: 21 processes: 10 internal, 11 linux-sandbox.
INFO: Build completed successfully, 21 total actions
INFO: Analyzed 366 targets (0 packages loaded, 8 targets configured).
INFO: Found 240 targets and 126 test targets...
INFO: Elapsed time: 71.923s, Critical Path: 23.19s
INFO: 131 processes: 138 linux-sandbox, 17 local.
INFO: Build …
> [Thinkit] Added GenericTestbed and ControlInterface interfaces. 

- lib/validator/validator_lib.cc
Change CheckAllInterfaceUpOverGnmi function to CheckAllInterfaceOperStateOverGnmi.BERT test.
Keyword Check:
Build Results:
INFO: Analyzed 367 targets (0 packages loaded, 0 targets configured).
INFO: Found 367 targets...
INFO: Elapsed time: 0.658s, Critical Path: 0.01s
UT Results:
INFO: Analyzed 367 …
> [Thinkit] Build failure fix.

- lib/ixia_helper.cc
- lib/ixia_helper.h
INFO: Analyzed 373 targets (0 packages loaded, 0 targets configured).
INFO: Found 373 targets...
INFO: Elapsed time: 0.524s, Critical Path: 0.00s
INFO: Analyzed 373 targets (2 packages loaded, 103 targets configured).
INFO: Found 373 targets...
INFO: Elapsed time: 19.009s, Critical Path: 18.05s
INFO: Analyzed 373 targets (0 packages …
> [Thinkit] Add APIs

- lib/BUILD.bazel
- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
- lib/pins_control_device.cc
- lib/pins_control_device.h
- lib/validator/BUILD.bazel
- lib/validator/validator_lib.cc
Add helper method to wait for gNMI config to converge.Rename GpinsControlDevice to PinsControlDevice and update P4RT trap request.
Keyword Check:
Build Results:
INFO: Analyzed 377 targets (1 packages loaded, 19 targets configured).
INFO: Found 377 targets...
INFO: Elapsed time: 22.333s, Critical Path: 10.06s
INFO: 6 processes: 1 internal, 5 linux-sandbox.
INFO: Build completed successfully, 6 total actions
UT Results:
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test …
> [Thinkit] Add helper method to wait for gNMI config to converge.Rename GpinsControlDevice to PinsControlDevice and update P4RT trap request.

- lib/utils/BUILD.bazel
- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 381 targets (1 packages loaded, 10 targets configured).
INFO: Found 381 targets...
INFO: From Compiling lib/utils/json_utils.cc:
...
INFO: Elapsed time: 18.841s, Critical Path: 18.24s
INFO: 13 processes: 5 internal, 8 linux-sandbox.
INFO: Build completed successfully, 13 total actions
INFO: Analyzed 381 targets (0 packages loaded, 2 targets configured).
INFO: Found 250 targets and 131 test targets...
INFO: Elapsed time: 63.545s, Critical Path: 16.29s
INFO: 136 …
> [Thinkit] [1/4] Create library for parsing and comparing json strings using json library.

- lib/utils/BUILD.bazel
- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 381 targets (1 packages loaded, 10 targets configured).
INFO: Found 381 targets...
INFO: From Compiling lib/utils/json_utils.cc:
...
INFO: Elapsed time: 5.783s, Critical Path: 5.26s
INFO: 9 processes: 4 internal, 5 linux-sandbox.
INFO: Analyzed 381 targets (0 packages loaded, 2 targets configured).
INFO: Found 250 targets and 131 test targets...
INFO: Elapsed time: 73.659s, Critical Path: 22.19s
INFO: 136 processes: …
> [Thinkit] [2/4] Create library for parsing and comparing json strings using json library.

- lib/utils/BUILD.bazel
- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 381 targets (0 packages loaded, 0 targets configured).
INFO: Found 381 targets...
...
INFO: Elapsed time: 6.188s, Critical Path: 5.69s
INFO: 7 processes: 2 internal, 5 linux-sandbox.
INFO: Build completed successfully, 7 total actions
INFO: Analyzed 381 targets (0 packages loaded, 0 targets configured).
INFO: Found 250 targets and 131 test targets...
INFO: Elapsed time: 72.303s, Critical Path: 16.27s
INFO: Build completed successfully, 136 total actions
//gutil:collections_test                                                 PASSED …
> [Thinkit] [3/4] Create library for parsing and comparing json strings using json library.

- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (1 packages loaded, 66 targets configured).
...
INFO: Elapsed time: 128.400s, Critical Path: 25.69s
INFO: 64 processes: 15 internal, 49 linux-sandbox.
INFO: Build completed successfully, 64 total actions
INFO: Analyzed 382 targets (0 packages loaded, 285 targets configured).
INFO: Elapsed time: 71.438s, Critical Path: 16.38s
INFO: …
> [Thinkit] Add support for ignoring unknown keys in the Flatten function.

- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (1 packages loaded, 66 targets configured).
...
INFO: Elapsed time: 128.400s, Critical Path: 25.69s
INFO: 64 processes: 15 internal, 49 linux-sandbox.
INFO: Build completed successfully, 64 total actions
INFO: Analyzed 382 targets (0 packages loaded, 285 targets configured).
INFO: Elapsed time: 71.438s, Critical Path: 16.38s
INFO: …
> [Thinkit] Implement a helper function to replace names in JSON object in place & Disable exceptions in ParseJson.

- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (1 packages loaded, 66 targets configured).
...
INFO: Elapsed time: 16.191s, Critical Path: 15.67s
INFO: Analyzed 382 targets (0 packages loaded, 285 targets configured).
INFO: Elapsed time: 71.438s, Critical Path: 16.38s
INFO: Build …
> [Thinkit] Adding a util function to check equivalence of 2 nlohmann::json objects.

- lib/validator/BUILD.bazel
- lib/validator/validator_lib.h
- lib/validator/validator_lib_test.cc
Add an API to wait for a validation to pass.
Keyword Check:
Build Results:
INFO: Analyzed 383 targets (0 packages loaded, 0 targets configured).
INFO: Found 383 targets...
INFO: Elapsed time: 0.896s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 383 targets (0 packages loaded, 2 targets …
> [Comb] Add an API to wait for a validation to pass.

- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
...
INFO: Elapsed time: 16.013s, Critical Path: 15.55s
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
INFO: Elapsed time: 62.326s, Critical Path: 16.62s
INFO: Build completed successfully, 136 total actions
//gutil:collections_test …
> [Thinkit] Adding GetSimpleJsonValue() to yang_json namespace & Add function for best-effort formatting of JSON strings. 

- lib/utils/BUILD.bazel
- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
...
INFO: Elapsed time: 16.013s, Critical Path: 15.55s
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
INFO: Elapsed time: 62.326s, Critical Path: 16.62s
INFO: Build completed successfully, 136 total actions
//gutil:collections_test PASSED in 0.5s
//gutil:io_test PASSED in 0.5s …
> [Thinkit] Accommodate objects with more than one key in FlattenJsonToMap().

- lib/utils/BUILD.bazel
- lib/utils/json_utils.cc
- lib/utils/json_utils.h
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
...
INFO: Elapsed time: 16.013s, Critical Path: 15.55s
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
INFO: Elapsed time: 62.326s, Critical Path: 16.62s
INFO: Build completed successfully, 136 total actions
//gutil:collections_test PASSED in 0.5s
//gutil:io_test PASSED in 0.5s …
> [Thinkit] Adding a IsJsonSubset() that accepts flattened JSON maps as input. 

- tests/lib/BUILD.bazel
- tests/lib/switch_test_setup_helpers.cc
- tests/lib/switch_test_setup_helpers.h
Add auxiliary function for switch and P4RT configuration.
Keyword Check:
Build Results:
INFO: Analyzed 384 targets (0 packages loaded, 0 targets configured).
INFO: Found 384 targets...
INFO: Elapsed time: 0.617s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 384 targets (0 packages loaded, …
> [Thinkit] Add auxiliary function for switch and P4RT configuration.

- lib/p4rt/BUILD.bazel
- lib/p4rt/p4rt_port_test.cc
INFO: Analyzed 386 targets (0 packages loaded, 0 targets configured).
INFO: Found 386 targets...
INFO: From Compiling lib/basic_traffic/basic_traffic.cc:
...
INFO: Elapsed time: 22.059s, Critical Path: 19.72s
INFO: 13 processes: 3 internal, 10 linux-sandbox.
INFO: Build completed successfully, 13 total actions
INFO: Analyzed 386 targets (0 packages loaded, 288 targets configured).
INFO: Found 252 targets and 134 test targets...
INFO: Elapsed time: 85.544s, Critical Path: 22.26s …
> [Thinkit] Adding p4rt port test file.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/ixia_helper.cc
- lib/ixia_helper.h
INFO: Analyzed 385 targets (0 packages loaded, 0 targets configured).
INFO: Found 385 targets...
...
INFO: Elapsed time: 101.438s, Critical Path: 28.15s
INFO: 24 processes: 3 internal, 21 linux-sandbox.
INFO: Build completed successfully, 24 total actions
INFO: Analyzed 385 targets (0 packages loaded, 287 targets configured).
INFO: Found 252 targets and 133 test targets...
INFO: Elapsed time: 67.797s, Critical Path: 16.35s
INFO: 138 processes: 145 linux-sandbox, 17 local.
INFO: …
> [Comb] Move utilities to common libraries & Add provision to pass in ingress and egress ports.

- lib/basic_traffic/BUILD.bazel
- lib/basic_traffic/basic_p4rt_util.cc
- lib/basic_traffic/basic_p4rt_util_test.cc
Make neighbor_id an IPv6 address and update tunnels to refer to it properly. Adding basic_p4rt_util_test to basic_traffic.
Keyword Check:
Build Results:
INFO: Analyzed 386 targets (0 packages loaded, 0 targets configured).
INFO: Found 386 targets...
INFO: Elapsed time: 0.629s, Critical Path: 0.00s
UT Results:
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS …
> [Comb] Make neighbor_id an IPv6 address and update tunnels to refer to it properly. Adding basic_p4rt_util_test to basic_traffic.

- lib/basic_traffic/basic_traffic.cc
- lib/pins_control_device.cc
- lib/pins_control_device.h
- thinkit/BUILD.bazel
- thinkit/control_device.h
- thinkit/mock_control_device.h
gNMI port mtu tests
Keyword Check:
Build Results:
INFO: Analyzed 387 targets (0 packages loaded, 0 targets configured).
INFO: Elapsed time: 1.067s, Critical Path: 0.00s
UT Results: 
INFO: Analyzed 387 targets (0 packages loaded, 33 targets configured).
INFO: Found …
> [Comb] gNMI port mtu tests

- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
INFO: From Compiling lib/gnmi/gnmi_helper.cc:
...
INFO: Elapsed time: 86.616s, Critical Path: 24.60s
INFO: 56 processes: 17 internal, 39 linux-sandbox.
INFO: Build completed successfully, 56 total actions
INFO: Elapsed time: 87.249s, Critical Path: 25.80s …
> [Thinkit] Add a util function to append sFlow-related config in gNMI config & Support parsing multiple key value in gNMI path.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
INFO: From Compiling lib/gnmi/gnmi_helper.cc:
...
INFO: Elapsed time: 53.250s, Critical Path: 22.66s
INFO: 23 processes: 3 internal, 20 linux-sandbox.
INFO: Build completed successfully, 23 total actions
INFO: Elapsed time: 87.249s, Critical Path: 25.80s …
> [Thinkit] Add in mfg-name and serial-no for future use-cases, No-Op & Make SetInterfaceP4rtIds ignore already correct interfaces.

- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
- lib/gnmi/openconfig.proto
INFO: From Compiling lib/gnmi/gnmi_helper.cc:
...
INFO: Elapsed time: 53.250s, Critical Path: 22.66s
INFO: 23 processes: 3 internal, 20 linux-sandbox.
INFO: Build completed successfully, 23 total actions
INFO: Elapsed time: 87.249s, Critical Path: 25.80s …
> [Comb] Include State in OpenConfig interface proto & Add support to get counters in gnmi_helper.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
INFO: From Compiling lib/gnmi/gnmi_helper.cc:
...
INFO: Elapsed time: 86.616s, Critical Path: 24.60s
INFO: 56 processes: 17 internal, 39 linux-sandbox.
INFO: Build completed successfully, 56 total actions
INFO: Elapsed time: 87.249s, Critical Path: 25.80s …
> [Thinkit] Add timestamp to PortCounters, Add _ns suffix to clarify timestamp units & Set Counters default values to 0.

- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
- lib/p4rt/p4rt_port.h
INFO: Analyzed 387 targets (1 packages loaded, 23 targets configured).
...
INFO: Elapsed time: 63.638s, Critical Path: 24.58s
INFO: 34 processes: 11 internal, 23 linux-sandbox.
INFO: Build completed successfully, 34 total actions
INFO: Elapsed time: 81.632s, Critical Path: 25.83s
INFO: Build completed successfully, 140 total actions
//gutil:collections_test PASSED in 0.5s
//gutil:io_test PASSED in 0.5s …
> [Thinkit] Make GetGnmiConfig output a valid gNMI Config.

- lib/basic_traffic/basic_traffic.cc
- lib/p4rt/BUILD.bazel
- lib/p4rt/packet_listener.cc
- lib/p4rt/packet_listener.h
- lib/pins_control_device.cc
- lib/pins_control_device.h
- thinkit/BUILD.bazel
- thinkit/control_device.h
- thinkit/mock_control_device.h
- thinkit/packet_generation_finalizer.h
Remove threading from PacketListener. Added basic_traffic_test.cc to basic_traffic. Added support for multiple interface modes in InterfaceInfo as hosts are considered to be both Control Device and Traffic Generator from the tests using GenericTestbed point of view.
Keyword Check:
Build Results:
INFO: Analyzed 388 targets (0 packages loaded, 0 targets configured).
INFO: Found 388 targets...
INFO: Elapsed time: 0.670s, Critical Path: 0.00s …
> [Comb] Remove threading from PacketListener. 

- sai_p4/instantiations/google/BUILD.bazel
- sai_p4/instantiations/google/sai_p4info_test.cc
Introduce bare-bones library for semantic versioning
Keyword Check:
Build Results:
INFO: Analyzed 388 targets (0 packages loaded, 0 targets configured).
INFO: Found 388 targets...
INFO: Elapsed time: 1.004s, Critical Path: 0.01s
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$
UT Results:
INFO: Analyzed 388 targets (0 packages loaded, 290 …
> [SAI_P4] Introduce bare-bones library for semantic versioning.

- p4rt_app/BUILD.bazel
- p4rt_app/p4rt.cc
- p4rt_app/p4runtime/BUILD.bazel
- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/p4runtime/p4runtime_impl.h
- p4rt_app/sonic/adapters/BUILD.bazel
- p4rt_app/sonic/adapters/fake_warm_boot_state_adapter.cc
- p4rt_app/sonic/adapters/fake_warm_boot_state_adapter.h
- p4rt_app/sonic/adapters/fake_warm_boot_state_adapter_test.cc
- p4rt_app/sonic/adapters/mock_warm_boot_state_adapter.h
- p4rt_app/sonic/adapters/warm_boot_state_adapter.cc
- p4rt_app/sonic/adapters/warm_boot_state_adapter.h
- p4rt_app/tests/BUILD.bazel
- p4rt_app/tests/grpc_behavior_test.cc
- p4rt_app/tests/lib/BUILD.bazel
- p4rt_app/tests/lib/p4runtime_grpc_service.cc
- p4rt_app/tests/lib/p4runtime_grpc_service.h
divya@cfdc38a2acd6:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 392 targets (0 packages loaded, 0 targets configured).
INFO: Found 392 targets...
INFO: Elapsed time: 59.944s, Critical Path: 30.66s
INFO: 23 processes: 2 internal, 21 linux-sandbox.
INFO: Build completed successfully, 23 total actions
divya@cfdc38a2acd6:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 392 targets (0 packages loaded, 44 targets configured).
INFO: Found 255 targets and 137 test targets...
INFO: Elapsed time: 95.550s, Critical Path: 25.75s
INFO: 142 processes: 149 linux-sandbox, 17 local.
INFO: Build completed successfully, 142 total actions
//gutil:collections_test …
> [P4RT] Add warm-boot adapter in P4RT.

- gutil/BUILD.bazel
- gutil/syslog_sink.cc
- gutil/syslog_sink.h
- p4rt_app/BUILD.bazel
- p4rt_app/p4rt.cc
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1619053724 -0700"
DEBUG: Repository com_github_nelhage_rules_boost instantiated at:
/sonic/src/sonic-p4rt/sonic-pins/WORKSPACE.bazel:75:9: in <toplevel>
/var/divya/.cache/bazel/_bazel_divya/5fd88bad78ef03829a4685c83637a020/external/com_github_p4lang_p4c/bazel/p4c_deps.bzl:25:23: in p4c_deps
Repository rule git_repository defined at:
/var/divya/.cache/bazel/_bazel_divya/5fd88bad78ef03829a4685c83637a020/external/bazel_tools/tools/build_defs/repo/git …
> [Comb] Add syslog sink to be used with GLOG.

- tests/lib/p4rt_fixed_table_programming_helper.cc
- tests/lib/p4rt_fixed_table_programming_helper.h
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 392 targets (1 packages loaded, 19 targets configured).
INFO: Found 392 targets...
INFO: From Compiling p4rt_app/scripts/p4rt_route_measurement_test.cc:
...
INFO: Elapsed time: 41.811s, Critical Path: 41.11s
INFO: 10 processes: 3 internal, 7 linux-sandbox.
INFO: Build completed successfully, 10 total actions
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 392 targets (0 packages loaded, 0 targets configured).
INFO: Found 255 targets and 137 test targets...
INFO: Elapsed time: 81.945s, Critical Path: …
> [Thinkit] Add a test for ensuring referenced entries can't be deleted.

- p4rt_app/scripts/BUILD.bazel
- p4rt_app/scripts/p4rt_route_measurement_test.cc
- tests/lib/p4rt_fixed_table_programming_helper.cc
- tests/lib/p4rt_fixed_table_programming_helper.h
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 392 targets (1 packages loaded, 19 targets configured).
INFO: Found 392 targets...
INFO: From Compiling p4rt_app/scripts/p4rt_route_measurement_test.cc:
...
INFO: Elapsed time: 41.811s, Critical Path: 41.11s
INFO: 10 processes: 3 internal, 7 linux-sandbox.
INFO: Build completed successfully, 10 total actions
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 392 targets (0 packages loaded, 0 targets configured).
INFO: Found 255 targets and 137 test targets...
INFO: Elapsed time: 81.945s, Critical Path: 25.75s
INFO: 142 processes: 149 linux-sandbox, 17 local.
INFO: Build completed successfully, 142 total actions …
> [Comb] Tunnel table prog measurement tests.

- p4rt_app/sonic/adapters/BUILD.bazel
- p4rt_app/sonic/adapters/mock_subscriber_state_table_adapter.h
- p4rt_app/sonic/adapters/subscriber_state_table_adapter.cc
- p4rt_app/sonic/adapters/subscriber_state_table_adapter.h
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 397 targets (243 packages loaded, 19854 targets configured).
INFO: Found 397 targets...
INFO: From Compiling P4 program p4_pdpi/testing/testdata/main.p4:
...
INFO: Elapsed time: 62.794s, Critical Path: 44.16s
INFO: 122 processes: 11 internal, 111 linux-sandbox.
INFO: Build completed successfully, 122 total actions
divya@529ce8414f42:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 397 targets (0 packages loaded, 292 targets configured).
INFO: Found 259 targets and 138 …
> [P4RT] Adding subscriber_state_table_adapter files.

- p4_pdpi/built_ins.cc
- p4_pdpi/built_ins.h
- p4_pdpi/helpers.cc
- p4_pdpi/helpers_test.cc
- p4_pdpi/ir.cc
- p4_pdpi/ir.proto
- p4_pdpi/testing/testdata/info.expected
- p4_pdpi/testing/testdata/main.p4
- p4_pdpi/testing/testdata/main_p4_pd.expected
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ./key.sh p4_pdpi/
/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS  ...
INFO: Analyzed 395 targets (0 packages loaded, 0 targets configured).
INFO: Found 395 targets...
INFO: From Compiling P4 program p4_pdpi/testing/testdata/main.p4:
p4_pdpi/testing/testdata/main.p4(60): [--Wwarn=unused] warning: 'arg1' is unused
action do_thing_1(@id(2) bit<32> arg1, @id(1) bit<32> arg2) {
^^^^
p4_pdpi/testing/testdata/main.p4(60): [--Wwarn=unused] warning: 'arg2' is unused
action do_thing_1(@id(2) bit<32> arg1, @id(1) bit<32> arg2) {
In file included from p4_pdpi/testing/table_entry_gunit_test.cc:18:
./p4_pdpi/pd.h:268:30: note: declared here
268 | absl::StatusOr<IrTableEntry> PartialPdTableEntryToIrTableEntry(
| …
> [P4-PDPI] Add built-in Clone Session.Add second action to golden test friendly wcmp table, so that different actions can be used in a set.

- p4_pdpi/BUILD.bazel
- p4_pdpi/references.cc
- p4_pdpi/references.h
- p4_pdpi/references_test.cc
- p4_pdpi/testing/BUILD.bazel
- p4_pdpi/testing/references_test_runner.cc
- p4_pdpi/testing/testdata/references.expected
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_checks.sh .
/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS  ...
INFO: Analyzed 401 targets (243 packages loaded, 19863 targets configured).
INFO: Found 401 targets...
INFO: From Compiling sai_p4/instantiations/google/test_tools/test_entries.cc:
In file included from ./gutil/proto.h:26,
from sai_p4/instantiations/google/test_tools/test_entries.cc:30:
sai_p4/instantiations/google/test_tools/test_entries.cc: In function 'absl::lts_20230802::StatusOr<std::vector<p4::v1::TableEntry> > sai::MakePiEntriesForwardingIpPacketsToGivenPort(absl::lts_20230802::string_view, const pdpi::IrP4Info&)':
sai_p4/instantiations/google/test_tools/test_entries.cc:144:75: …
> [P4-PDPI] Add references library to help handle p4 table entry dependencies.

- p4_fuzzer/BUILD.bazel
- p4_fuzzer/oracle_util_test.cc
divya@3c5359ef48c4:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...                        
INFO: Analyzed 398 targets (0 packages loaded, 293 targets configured).
INFO: Found 398 targets...
...
INFO: Elapsed time: 305.328s, Critical Path: 68.48s
INFO: 896 processes: 375 internal, 504 linux-sandbox, 17 local.
INFO: Build completed successfully, 896 total actions
divya@3c5359ef48c4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 398 targets (0 packages loaded, 0 targets configured).
INFO: Found 259 targets and 139 test targets...
INFO: Elapsed time: 92.586s, Critical Path: 25.74s
INFO: 144 processes: …
> [P4_Fuzzer] Fix oracle_util_test.

- p4_pdpi/testing/testdata/sequencing.expected
divya@311bb836ebef:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...                        
INFO: Analyzed 404 targets (0 packages loaded, 298 targets configured).
INFO: Found 404 targets...
INFO: Elapsed time: 2.148s, Critical Path: 0.02s
divya@311bb836ebef:/sonic/src/sonic-p4rt/sonic-pins$ 
divya@311bb836ebef:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 404 targets (0 packages loaded, 0 targets configured).
INFO: Found 260 targets and 144 test targets...
...
INFO: Elapsed time: 2487.492s, Critical Path: 146.93s
INFO: 4633 processes: 4644 linux-sandbox, 17 local.
INFO: Build completed successfully, 4633 total actions …
> [Misc] PDPI Build fix.

- p4rt_app/sonic/app_db_to_pdpi_ir_translator.cc
- p4rt_app/sonic/app_db_to_pdpi_ir_translator_test.cc
- p4rt_app/sonic/packet_replication_entry_translation.cc
- p4rt_app/sonic/packet_replication_entry_translation_test.cc
- p4rt_app/sonic/state_verification_test.cc
- p4rt_app/tests/forwarding_pipeline_config_test.cc
- p4rt_app/tests/packet_replication_table_test.cc
divya@a17da3ffc51c:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 408 targets (0 packages loaded, 29 targets configured).
INFO: Found 408 targets...
...
INFO: Elapsed time: 2248.676s, Critical Path: 92.81s
INFO: 9139 processes: 2723 internal, 6416 linux-sandbox.
INFO: Build completed successfully, 9139 total actions
divya@a17da3ffc51c:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1619053724 -0700"
DEBUG: Repository com_github_nelhage_rules_boost …
> [P4RT] Use consistent 16-bit hex strings for `multicast_group_id` and `multicast_replica_instance`.

- gutil/status.h
- p4_pdpi/packetlib/BUILD.bazel
- p4_pdpi/packetlib/packetlib_test_runner.cc
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Tools/keyword_checks.sh .
INFO: Analyzed 408 targets (150 packages loaded, 18986 targets configured).
INFO: Found 408 targets...
INFO: From Compiling p4_pdpi/netaddr/mac_address.cc:
In file included from ./p4_pdpi/netaddr/network_address.h:28,
from ./p4_pdpi/netaddr/ipv6_address.h:23,
from ./p4_pdpi/netaddr/mac_address.h:22,
from p4_pdpi/netaddr/mac_address.cc:14:
./p4_pdpi/string_encodings/hex_string.h: In instantiation of 'std::string pdpi::BitsetToHexString(const std::bitset<_Nb>&) [with long unsigned int num_bits = 64; std::string = std::__cxx11::basic_string<char>]':
p4_pdpi/netaddr/mac_address.cc:103:78:   required from here …
> [Comb] Adds `StreamableStatusOr` utility and removed `absl::StatusOr` `operator<<` overloads.

- p4_pdpi/built_ins.cc
- p4_pdpi/built_ins.h
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Tools/keyword_checks.sh .
INFO: Analyzed 408 targets (0 packages loaded, 0 targets configured).
INFO: Found 408 targets...
INFO: From Compiling p4_pdpi/ir.cc:
In file included from ./gutil/collections.h:29,
from p4_pdpi/ir.cc:44:
p4_pdpi/ir.cc: In function 'absl::lts_20230802::StatusOr<pdpi::IrP4Info> pdpi::CreateIrP4Info(const p4::config::v1::P4Info&)':
p4_pdpi/ir.cc:1486:73: warning: 'absl::lts_20230802::StatusOr<std::vector<pdpi::IrMatchFieldReference> > pdpi::{anonymous}::GetRefersToAnnotations(const p4::config::v1::P4Info&, const google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char> >&)' is deprecated: Use ParseRefersToAnnotations …
> [Comb] Match action coverage test now covers multicast group table.

- p4_symbolic/symbolic/test.bzl
- p4_symbolic/symbolic/util.cc
- p4_symbolic/symbolic/util.h
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Tools/keyword_checks.sh .
DEBUG: Rule 'sonic_swss_common' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fbd1f2ef83af06af744491253a66315b8bfe64227e19f0357c2fb560a8da57f0"
DEBUG: Repository sonic_swss_common instantiated at:
/sonic/src/sonic-p4rt/sonic-pins/WORKSPACE.bazel:19:16: in <toplevel>
/sonic/src/sonic-p4rt/sonic-pins/pins_infra_deps.bzl:239:21: in pins_infra_deps
Repository rule http_archive defined at:
/var/vsurya/.cache/bazel/_bazel_vsurya/5fd88bad78ef03829a4685c83637a020/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed 410 targets (1 packages loaded, 71 …
> [P4-Symbolic] Adding files in p4_symbolic

- p4_symbolic/ir/BUILD.bazel
- p4_symbolic/ir/pdpi_driver.cc
- p4_symbolic/ir/pdpi_driver.h
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Tools/keyword_checks.sh .
/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...          
2024/09/10 06:06:05 Downloading https://releases.bazel.build/5.1.0/release/bazel-5.1.0-linux-x86_64...
Downloading: 49 MB out of 49 MB (100%) 
Extracting Bazel installation...
DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1619053724 -0700"
DEBUG: Repository com_github_nelhage_rules_boost instantiated at:
/sonic/src/sonic-p4rt/sonic-pins/WORKSPACE.bazel:75:9: in <toplevel>
In file included from p4rt_app/tests/port_name_and_id_test.cc:29: …
> [P4-Symbolic] Adding BUILD.bazel, pdpi_driver.cc, pdpi_driver.h files to p4_symbolic/ir

- p4_symbolic/packet_synthesizer/BUILD.bazel
- p4_symbolic/packet_synthesizer/packet_synthesizer.proto
Keyword Check:
eonms6vm2@eonms6vm2:~/psj-sonic-pins/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/key_check.sh .
Build and Test Results:
...
INFO: Elapsed time: 3331.898s, Critical Path: 925.27s
INFO: 9350 processes: 2819 internal, 6531 linux-sandbox.
INFO: Build completed successfully, 9350 total actions
eonms6vm2@6c57970698de:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
...
INFO: Found 314 targets and 163 test targets...
INFO: Elapsed time: 123.711s, Critical Path: 25.92s
INFO: 168 processes: 194 linux-sandbox, 18 local.
INFO: Build completed successfully, 168 total actions
//gutil:collections_test                                                 PASSED in 0.5s
//gutil:io_test …
> [p4-symbolic] Adding packet_synthesizer proto file.

- p4_fuzzer/BUILD.bazel
- p4_fuzzer/fuzz_util.cc
- p4_fuzzer/fuzz_util.h
- p4_fuzzer/fuzzer.proto
- p4_fuzzer/fuzzer_config.h
- p4_fuzzer/mutation.cc
- p4_fuzzer/mutation.h
Key word check:
```
pins_upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh p4_fuzzer/
```
Build result:
```
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
INFO: Analyzed 475 targets (249 packages loaded, 22426 targets configured).
INFO: Found 475 targets...
INFO: Elapsed time: 401.069s, Critical Path: 58.30s
```
Test result:
```
INFO: Analyzed 475 targets (0 …
```
> improve the precision of the fuzzer.

- p4_symbolic/symbolic/guarded_map.cc
- p4_symbolic/symbolic/guarded_map.h
- p4_symbolic/symbolic/operators.cc
- p4_symbolic/symbolic/operators.h
Keyword Check :
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh .
Build Result:
INFO: Analyzed 514 targets (0 packages loaded, 324 targets configured).
INFO: Found 514 targets...
INFO: From Compiling p4_symbolic/symbolic/values.cc [for host]:
In file included from ./p4_pdpi/netaddr/network_address.h:28,
                from ./p4_pdpi/netaddr/ipv4_address.h:22,
                from p4_symbolic/symbolic/values.cc:34:
./p4_pdpi/string_encodings/hex_string.h: In instantiation of 'std::string pdpi::BitsetToHexString(const std::bitset<_Nb>&) [with long unsigned int num_bits = 32; std::string = std::__cxx11::basic_string<char>]':
./p4_pdpi/netaddr/network_address.h:86:67:   required …
> [P4-Symbolic] Fix implementation of shift and add support forbitvector slicing.

- tests/gnoi/factory_reset_test.cc
Enable gNOI factory reset test response checking.
Keyword Check:
bibhuprasad@bibhuprasad9136:~/Sonic_Build_20_11/sonic-buildimage/src/sonic-p4rt/sonic-pins$~/keyword_check.sh .
Build Results:
bibhuprasad@0d913d59fd9f:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 598 targets (0 packages loaded, 0 targets configured).
INFO: Found 598 targets...
INFO: Elapsed time: 0.575s, Critical Path: 0.01s
bibhuprasad@0d913d59fd9f:/sonic/src/sonic-p4rt/sonic-pins$
UT Results:
bibhuprasad@0d913d59fd9f:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 598 targets (0 packages loaded, 352 targets …
> [Thinkit] Enable gNOI factory reset test response checking.

- tests/sflow/BUILD.bazel
- tests/sflow/sflow_test.cc
- tests/sflow/sflow_test.h
- tests/sflow/sflow_util.cc
- tests/sflow/sflow_util.h
- tests/sflow/sflow_util_test.cc
Key_word Check:
```
~/pins_upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins/tests/sflow$ ~/tools/keyword_checks.sh .
```
Build result:
```
INFO: Analyzed 636 targets (0 packages loaded, 0 targets configured).
INFO: Found 636 targets...
INFO: Elapsed time: 0.444s, Critical Path: 0.00s
```
Test result:
```
INFO: Analyzed 636 targets (0 packages loaded, 0 targets configured).
INFO: Found 424 targets and 212 test targets...
INFO: Elapsed time: 161.726s, Critical Path: 116.14s
INFO: 266 processes: 321 linux-sandbox, 18 local.
INFO: …
```
> [Thinkit] Add a test case for sFlow backoff. Add a util function to verify dscp value.

- .github/workflows/ci.yml
- pins_infra_deps.bzl
Description:
```
Updating action/cache version V2 to V3
```
Build result:
```
INFO: Analyzed 671 targets (27 packages loaded, 1452 targets configured).
INFO: Found 671 targets...
INFO: Elapsed time: 2.521s, Critical Path: 0.04s
```
Test result:
```
INFO: Analyzed 673 targets (0 packages loaded, 372 targets configured).
INFO: Found 456 targets and 217 test targets...
INFO: Elapsed time: 165.434s, Critical Path: 119.58s
INFO: 270 processes: 326 linux-sandbox, 18 local.
INFO: Build completed successfully, 270 total actions
//dvaas:port_id_map_test …
```
> [pins_workflow] Improve GitHub continuous integration performance.

- tests/integration/system/nsf/flow_programmers/BUILD.bazel
- tests/integration/system/nsf/flow_programmers/fuzzer_replay_programmer.h
- tests/integration/system/nsf/flow_programmers/replay_programmer.h
- tests/integration/system/nsf/flow_programmers/static_programmer.h
Key_word Check:
```
~/pins_upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins/tests/sflow$ ~/tools/keyword_checks.sh .
```
Build result:
```
INFO: Analyzed 671 targets (27 packages loaded, 1452 targets configured).
INFO: Found 671 targets...
INFO: Elapsed time: 2.521s, Critical Path: 0.04s
```
Test result:
```
INFO: Analyzed 673 targets (0 packages loaded, 372 targets configured).
INFO: Found 456 targets and 217 test targets...
INFO: Elapsed time: 165.434s, Critical Path: 119.58s
INFO: 270 processes: 326 linux-sandbox, 18 local. …
```
> [Thinkit] Implement the various flow programmers for PINs NSF tests.

- p4_symbolic/ir/ir.proto
- p4_symbolic/symbolic/symbolic.cc
- p4_symbolic/symbolic/table_entry.cc
- p4_symbolic/symbolic/table_entry.h
- p4_symbolic/tests/BUILD.bazel
- p4_symbolic/tests/symbolic_table_entries_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 671 targets (1 packages loaded, 4 targets configured).
INFO: Found 671 targets...
INFO: From Compiling p4_symbolic/sai/sai.cc:
In file included from ./p4_symbolic/z3_util.h:18,
from ./p4_symbolic/symbolic/symbolic.h:36,
from ./p4_symbolic/sai/sai.h:24,
from p4_symbolic/sai/sai.cc:15:
./p4_pdpi/string_encodings/bit_string.h: In member function 'void pdpi::BitString::AppendBytes(absl::lts_20230802::string_view)':
./p4_pdpi/string_encodings/bit_string.h:55:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::basic_string_view<char>::size_type' {aka …
> [P4_Symbolic] Create symbolic variables and add constraints for symbolic table entries.

- p4_symbolic/ir/BUILD.bazel
- p4_symbolic/ir/expected/basic.txt
- p4_symbolic/ir/expected/table.txt
- p4_symbolic/ir/ir.cc
- p4_symbolic/ir/ir.h
- p4_symbolic/ir/ir.proto
- p4_symbolic/ir/table_entries.cc
- p4_symbolic/packet_synthesizer/criteria_generator.cc
- p4_symbolic/sai/BUILD.bazel
- p4_symbolic/sai/sai.cc
- p4_symbolic/symbolic/BUILD.bazel
- p4_symbolic/symbolic/action.cc
- p4_symbolic/symbolic/action.h
- p4_symbolic/symbolic/context.h
- p4_symbolic/symbolic/symbolic.cc
- p4_symbolic/symbolic/table.cc
- p4_symbolic/symbolic/table_entry.cc
- p4_symbolic/symbolic/table_entry.h
- p4_symbolic/symbolic/table_entry_test.cc
- p4_symbolic/symbolic/util.cc
- p4_symbolic/tests/symbolic_table_entries_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 690 targets (0 packages loaded, 0 targets configured).
INFO: Found 690 targets...
INFO: From Compiling p4_symbolic/ir/cfg.cc:
In file included from p4_symbolic/ir/cfg.cc:15:
./p4_symbolic/ir/cfg.h:79:3: warning: multi-line comment [-Wcomment]
79 |   //             /             \
|   ^
p4_symbolic/ir/cfg.cc:349:5: warning: multi-line comment [-Wcomment]
349 |     //      /  \
|     ^
p4_symbolic/ir/cfg.cc:388:7: warning: multi-line comment [-Wcomment]
388 |       //      /  \
|       ^
p4_symbolic/ir/cfg.cc: In function 'p4_symbolic::ir::ControlPath …
> [P4_Symbolic] Eliminate symbolic::TableEntry and use ir::TableEntry instead.

- tests/forwarding/l3_multicast_test.cc
- tests/forwarding/l3_multicast_test.h
Keyword Check:
Build Result:
INFO: Analyzed 692 targets (0 packages loaded, 0 targets configured).
INFO: Found 692 targets...
INFO: Elapsed time: 0.863s, Critical Path: 0.00s
Test Result:
INFO: Analyzed 692 targets (0 packages loaded, 0 targets configured).
INFO: Found 475 targets and 217 test targets...
INFO: Elapsed time: 190.118s, Critical Path: 114.53s
INFO: 271 processes: 326 linux-sandbox, 18 local.
INFO: Build completed successfully, 271 total actions …
> [Thinkit] Modified tests for multicast programming

- tests/forwarding/l3_multicast_test.cc
- tests/forwarding/l3_multicast_test.h
Keyword Check:
Build Result:
INFO: Analyzed 692 targets (0 packages loaded, 0 targets configured).
INFO: Found 692 targets...
INFO: Elapsed time: 0.774s, Critical Path: 0.00s
UT Result:
INFO: Analyzed 692 targets (0 packages loaded, 0 targets configured).
INFO: Found 475 targets and 217 test targets...
INFO: Elapsed time: 187.979s, Critical Path: 117.45s
INFO: 271 processes: 326 linux-sandbox, 18 local.
INFO: Build completed successfully, 271 total actions …
> [Thinkit] Add negative tests for L3 multicast programming. Add additional negative multicast programming tests

- tests/qos/BUILD.bazel
- tests/qos/frontpanel_qos_test.cc
- tests/qos/qos_test_util.cc
- tests/qos/qos_test_util.h
Exponentially increase PIR and fix datatypes. DSCP to Queue test for Multicast traffic.
bibhuprasad@bibhuprasad9136:~/Sonic_Build_20_11/sonic-buildimage/src/sonic-p4rt/sonic-pins$ sh ~/keyword_check.sh ./
bibhuprasad@abe92661eacf:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 695 targets (0 packages loaded, 0 targets configured).
INFO: Found 695 targets...
INFO: Elapsed time: 0.518s, Critical Path: 0.01s
bibhuprasad@abe92661eacf:/sonic/src/sonic-p4rt/sonic-pins$ 
bibhuprasad@abe92661eacf:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 695 targets (0 packages loaded, 374 targets configured).
INFO: …
> [Thinkit] Exponentially increase PIR and fix datatypes. DSCP to Queue test for Multicast traffic.

- tests/forwarding/l3_multicast_test.cc
- tests/forwarding/l3_multicast_test.h
Keyword Check:
Build Result:
INFO: Analyzed 695 targets (0 packages loaded, 0 targets configured).
INFO: Found 695 targets...
INFO: Elapsed time: 0.710s, Critical Path: 0.00s
UT Result:
INFO: Analyzed 695 targets (0 packages loaded, 0 targets configured).
INFO: Found 477 targets and 218 test targets...
INFO: Elapsed time: 218.779s, Critical Path: 123.48s
INFO: 275 processes: 330 linux-sandbox, 18 local.
INFO: Build completed successfully, 275 total actions …
> [Thinkit] Add multicast test using ACL redirect.Update expected error outputs for multicast tests

- tests/qos/BUILD.bazel
- tests/qos/frontpanel_qos_test.cc
Dynamic buffer test for multicast
bibhuprasad@bibhuprasad9136:~/Sonic_Build_20_11/sonic-buildimage/src/sonic-p4rt/sonic-pins$ sh ~/keyword_check.sh ./
bibhuprasad@abe92661eacf:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 696 targets (0 packages loaded, 0 targets configured).
INFO: Found 696 targets...
INFO: Elapsed time: 0.411s, Critical Path: 0.00s
bibhuprasad@abe92661eacf:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 696 targets (0 packages loaded, 0 targets configured).
INFO: Found 478 targets and 218 test targets...
INFO: Elapsed time: 161.584s, Critical Path: 116.26s
INFO: 275 processes: …
> [Thinkit] Dynamic buffer test for multicast

- WORKSPACE.bazel
- pins_infra_deps.bzl
Keyword Check:
~/sk/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh .
Build Result:
INFO: Analyzed 710 targets (1 packages loaded, 1135 targets configured).
INFO: Found 710 targets...
./gutil/status_matchers.h:63:43: note: in definition of macro 'ASSERT_OK_AND_ASSIGN'
63 |   auto __ASSIGN_OR_RETURN_VAL(__LINE__) = expression;                          \
|                                           ^~~~~~~~~~
In file included from p4_pdpi/ir_tools_test.cc:18:
./p4_pdpi/pd.h:292:30: note: declared here
292 | absl::StatusOr<IrTableEntry> PartialPdTableEntryToIrTableEntry(
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
p4_pdpi/ir_tools_test.cc:49:57: warning: …
> Updated Workspace name to match the repo.

- tests/qos/cpu_qos_test.cc
- tests/qos/cpu_qos_test.h
- tests/qos/frontpanel_qos_test.cc
- tests/qos/qos_test_util.cc
- tests/qos/qos_test_util.h
Key_word Check:
```
~/pins_upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins/tests/sflow$ ~/tools/keyword_checks.sh .
```
Build result:
```
/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ... 
INFO: Analyzed 710 targets (0 packages loaded, 0 targets configured).
INFO: Found 710 targets...
INFO: Elapsed time: 0.307s, Critical Path: 0.00s
```
Test result:
```
INFO: Analyzed 710 targets (0 packages loaded, 2 targets configured).
INFO: Found 488 targets and 222 test targets...
INFO: Elapsed time: 167.310s, Critical Path: 122.26s
INFO: 279 processes: 336 linux-sandbox, 18 local.
INFO: …
```
> [Thinkit] Add Bursty Traffic test to the CPUQosWithIxia Test

- p4rt_app/p4runtime/BUILD.bazel
- p4rt_app/p4runtime/p4info_reconcile.cc
- p4rt_app/p4runtime/p4info_reconcile.h
- p4rt_app/sonic/hashing.cc
- p4rt_app/sonic/hashing.h
- p4rt_app/sonic/hashing_test.cc
upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh  .
./p4_pdpi/string_encodings/bit_string.h: In instantiation of 'void pdpi::BitString::AppendBits(const std::bitset<_Nb>&) [with long unsigned int num_bits = 8]':
./p4_pdpi/string_encodings/bit_string.h:41:24:   required from here
./p4_pdpi/string_encodings/bit_string.h:49:23: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
49 |     for (int i = 0; i < num_bits; i++) {
|                     ~~^~~~~~~~~~
INFO: Elapsed time: 349.078s, Critical Path: 342.43s
INFO: 758 processes: 202 internal, 556 linux-sandbox.
INFO: Build completed successfully, 758 total actions
INFO: Build completed successfully, 758 total actions …
> [P4RT] Calculate hash config deltas during P4Reconcile.

- p4rt_app/scripts/BUILD.bazel
- p4rt_app/scripts/p4rt_route_measurement_test.cc
- tests/lib/p4rt_fixed_table_programming_helper.cc
- tests/lib/p4rt_fixed_table_programming_helper.h
**Keycheck Result:**
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_check.sh ./p4rt_app/ .
**Bazel Build Output:**
INFO: Analyzed 717 targets (0 packages loaded, 0 targets configured).
INFO: Found 717 targets...
INFO: From Compiling p4rt_app/scripts/p4rt_route_measurement_test.cc:
p4rt_app/scripts/p4rt_route_measurement_test.cc: In function 'absl::lts_20230802::Status p4rt_app::{anonymous}::VerifyP4WriteRequestSizes(const P4WriteRequests&, uint32_t, uint32_t, bool)':
p4rt_app/scripts/p4rt_route_measurement_test.cc:307:21: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<p4::v1::WriteRequest>::size_type' {aka 'long unsigned int'} [-Wsign-compare] …
> [P4RT]Update P4RT test to include on-SUT multicast programming,Port ID assignment and init time prior to performance testing.

- sai_p4/fixed/drop_martians.p4
- sai_p4/instantiations/google/BUILD.bazel
- sai_p4/instantiations/google/acl_ingress.p4
- sai_p4/instantiations/google/fabric_border_router.p4info.pb.txt
- sai_p4/instantiations/google/middleblock.p4info.pb.txt
- sai_p4/instantiations/google/preprocessed_sai_programs_test.cc
- sai_p4/instantiations/google/sai_nonstandard_platforms.cc
- sai_p4/instantiations/google/sai_nonstandard_platforms.h
- sai_p4/instantiations/google/sai_pd.proto
- sai_p4/instantiations/google/tor.p4info.pb.txt
- sai_p4/instantiations/google/unioned_p4info.pb.txt
Keyword Check:
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh .
Build Result:
INFO: Analyzed 725 targets (0 packages loaded, 0 targets configured).
INFO: Found 725 targets...
sai_p4/instantiations/google/../../fixed/mirroring.p4(33): [--Wwarn=unused] warning: Unused action parameter src_ip
@id(2) @format(IPV4_ADDRESS) ipv4_addr_t src_ip,
^^^^^^
sai_p4/instantiations/google/../../fixed/mirroring.p4(34): [--Wwarn=unused] warning: Unused action parameter dst_ip
@id(3) @format(IPV4_ADDRESS) ipv4_addr_t dst_ip,
^^^^^^
sai_p4/instantiations/google/../../fixed/mirroring.p4(35): [--Wwarn=unused] warning: Unused action parameter src_mac
@id(4) @format(MAC_ADDRESS) ethernet_addr_t …
> [SAI-P4] Adding Preprocess SAI P4 Programs for P4Testgen to produce tests without invoking its internal preprocessor

- lib/gnmi/BUILD.bazel
- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper_test.cc
- p4_pdpi/reference_annotations.cc
- p4_pdpi/reference_annotations.h
- p4_pdpi/reference_annotations_test.cc
- p4rt_app/sonic/app_db_acl_def_table_manager_test.cc
- p4rt_app/utils/ir_builder.h
- sai_p4/instantiations/google/BUILD.bazel
- sai_p4/instantiations/google/sai_p4info_test.cc
- sai_p4/instantiations/google/versions.h
Keyword Check:
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh .
Build Result:
INFO: Analyzed 727 targets (260 packages loaded, 22923 targets configured).
INFO: Found 727 targets...
tests/qos/cpu_qos_test.cc:1191:5: note: in expansion of macro 'ASSERT_OK'
1191 |     ASSERT_OK(pdpi::ClearTableEntries(sut_p4rt_session.get()));
|     ^~~~~~~~~
./p4_pdpi/p4_runtime_session.h:392:14: note: declared here
392 | absl::Status ClearTableEntries(P4RuntimeSession *session);
|              ^~~~~~~~~~~~~~~~~
tests/qos/cpu_qos_test.cc: In member function 'virtual void pins_test::{anonymous}::CpuQosTestWithoutIxia_P4CpuQueueMappingByNameIsCorrec …
> [Comb] Ensuring the Correct usage of Protobuf DebugString APIs.

- p4_pdpi/ir.cc
- p4_pdpi/ir.proto
- p4_pdpi/names.cc
- p4_pdpi/pd.cc
- p4_pdpi/testing/table_entry_gunit_test.cc
- p4_pdpi/testing/table_entry_test_runner.cc
- p4_pdpi/testing/testdata/table_entry.expected
Keyword Check Result:
~/tools/keyword_check.sh ./p4_pdpi/ .
Bazel Build Result:
INFO: Analyzed 727 targets (260 packages loaded, 22923 targets configured).
INFO: Found 727 targets...
INFO: From Compiling p4_pdpi/pd.cc:
In file included from ./p4_pdpi/pd.h:25,
from p4_pdpi/pd.cc:15:
p4_pdpi/pd.cc: In function 'absl::lts_20230802::StatusOr<p4::v1::TableEntry> pdpi::PartialPdTableEntryToPiTableEntry(const IrP4Info&, const google::protobuf::Message&, const TranslationOptions&)':
INFO: From Executing genrule //p4_symbolic/ir:partial_icmp_test_parse:
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20250516 13:30:52.988552     3 …
> [P4_PDPI] [P4 Infra] Support CloneSessionEntry translation between PI <-> IR.

- dvaas/BUILD.bazel
- dvaas/dataplane_validation.cc
- dvaas/dataplane_validation.h
- dvaas/packet_trace.proto
/dvass/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh .
INFO: Analyzed 729 targets (260 packages loaded, 22927 targets configured).
INFO: Found 729 targets...
INFO: From Generating C++ proto_library //dvaas:test_vector_proto:
dvaas/test_vector.proto:19:1: warning: Import dvaas/packet_trace.proto is unused.
INFO: From Generating Descriptor Set proto_library //dvaas:test_vector_proto:
dvaas/test_vector.proto:19:1: warning: Import dvaas/packet_trace.proto is unused.
INFO: From Compiling dvaas/test_vector.cc:
tests/forwarding/hash_testfixture.cc: At global scope:
tests/forwarding/hash_testfixture.cc:195:6: warning: 'void …
> [Dvaas] Added refactor packet_trace.proto and print all failed test outcomes traces to file

- tests/sflow/BUILD.bazel
- tests/sflow/sflow_test.cc
- tests/sflow/sflow_test.h
divyagayathris@divyagayathris-16:~/Apr11/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh tests/.
divyagayathris@2ef3a271cd98:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 734 targets (0 packages loaded, 0 targets configured).
INFO: Found 734 targets...
...
INFO: Elapsed time: 23.604s, Critical Path: 23.03s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
divyagayathris@2ef3a271cd98:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 734 targets (0 packages loaded, 3 targets configured).
INFO: Found 507 targets and 227 test targets...
INFO: Elapsed time: 178.044s, Critical Path: 131.77s
INFO: 284 processes: 340 …
> [Thinkit/Tests] Add NSF backoff test & to add checks for NSF reboot related tests.

- tests/qos/BUILD.bazel
- tests/qos/pfc_test.cc
- tests/qos/pfc_test.h
**Keyword Check Result:**
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_check.sh ./tests/.
**Bazel Build Result:**
INFO: Analyzed 733 targets (0 packages loaded, 0 targets configured).
INFO: Found 733 targets...
INFO: From Compiling tests/qos/pfc_test.cc:
tests/qos/pfc_test.cc: In member function 'virtual void pins_test::PfcTestWithIxia_PfcRxWithNoPacketDrops_Test::TestBody()':
tests/qos/pfc_test.cc:283:21: warning: loop variable '<structured bindings>' creates a copy from type 'const std::pair<const int, std::__cxx11::basic_string<char> >' [-Wrange-loop-construct]
283 |     for (const auto [priority, queue] : *GetParam().queue_by_pfc_priority) {
tests/qos/pfc_test.cc:283:21: note: use …
> [Thinkit/tests] Add a test for PFC Rx.

- lib/gnmi/gnmi_helper.cc
- lib/gnmi/gnmi_helper.h
- lib/gnmi/gnmi_helper_test.cc
- lib/ixia_helper.cc
- lib/ixia_helper.h
- tests/qos/BUILD.bazel
- tests/qos/pfc_test.cc
- tests/qos/pfc_test.h
**Keyword check Result:**
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_check.sh ./lib/.
**Bazel Build Result:**
INFO: Analyzed 733 targets (260 packages loaded, 22948 targets configured).
INFO: Found 733 targets...
INFO: Deleting stale sandbox base /var/jayaragini/.cache/bazel/_bazel_jayaragini/5fd88bad78ef03829a4685c83637a020/sandbox
INFO: From Compiling tests/sflow/sflow_test.cc:
In file included from tests/gnmi/counter_timestamp_test.cc:21:
./p4_pdpi/p4_runtime_session.h:392:14: note: declared here
392 | absl::Status ClearTableEntries(P4RuntimeSession *session);
|              ^~~~~~~~~~~~~~~~~
INFO: Elapsed time: 194.097s, …
> [Thinkit] Support new PFC + watchdog paths and Add an option to skip appending traffic type in SetTrafficParameters.

- dvaas/test_vector_stats_test.expected
- p4_symbolic/ir/table_entries.cc
- p4_symbolic/packet_synthesizer/BUILD.bazel
- p4_symbolic/packet_synthesizer/util.cc
- p4_symbolic/sai/BUILD.bazel
- p4_symbolic/sai/sai.cc
- p4_symbolic/sai/sai.h
Prevent synthesizing packets ingressing on ports that are configured to be
bibhuprasad@bibhuprasad87:~/sonic_build_image_2025-06-23/sonic-buildimage/src/sonic-p4rt/sonic-pins/p4_symbolic$ sh ~/keyword_check.sh .
bibhuprasad@b5d6b9918c77:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 740 targets (0 packages loaded, 0 targets configured).
INFO: Found 740 targets...
INFO: Elapsed time: 0.314s, Critical Path: 0.00s
bibhuprasad@b5d6b9918c77:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 740 targets (0 packages loaded, 0 targets configured).
INFO: Found 514 targets and 226 test targets...
INFO: …
> [P4_Symbolic] Prevent synthesizing packets ingressing on ports that are configured to be

- tests/forwarding/BUILD.bazel
- tests/forwarding/hash_statistics_util.cc
- tests/forwarding/hash_statistics_util.h
- tests/forwarding/hash_statistics_util_test.cc
- tests/forwarding/hash_testfixture.cc
- tests/forwarding/hash_testfixture.h
- tests/forwarding/multistage_hash_test.h
divyagayathris@divyagayathris-16:~/Apr11/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh tests/.
divyagayathris@0b1668e9d59a:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 743 targets (0 packages loaded, 0 targets configured).
INFO: Found 743 targets...
...
tests/integration/system/nsf/nsf_acl_flow_coverage_test.cc:114:29: warning: unused variable 'environment' [-Wunused-variable]
114 |   thinkit::TestEnvironment& environment = std::visit(
|                             ^~~~~~~~~~~
INFO: Elapsed time: 30.547s, Critical Path: 23.06s
INFO: 29 processes: 3 internal, 26 linux-sandbox.
INFO: Build completed successfully, 29 total actions
divyagayathris@0b1668e9d59a:/sonic/src/sonic-p4rt/sonic-pins$ bazel test …
> [Thinkit/Tests] Add support for WCMP testing with different member sizes.

- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/p4runtime/p4runtime_impl.h
- p4rt_app/sonic/app_db_manager_test.cc
- p4rt_app/tests/BUILD.bazel
- p4rt_app/tests/forwarding_pipeline_config_test.cc
divyagayathris@divyagayathris-16:~/Apr11/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh p4rt_app/.
divyagayathris@ee1687cf7625:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
...
p4rt_app/tests/packetio_test.cc:265:54:   required from here
./p4_pdpi/string_encodings/hex_string.h:95:24: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
INFO: Elapsed time: 192.312s, Critical Path: 135.87s
INFO: 340 processes: 392 linux-sandbox, 18 local.
INFO: Build completed successfully, 340 total actions
//dvaas:port_id_map_test                                                 PASSED in 2.7s
//dvaas:test_run_validation_golden_test …
> [P4RT] Move p4 constraint generated to config verification.

- dvaas/BUILD.bazel
- dvaas/arriba_test_vector_validation.cc
- dvaas/arriba_test_vector_validation.h
- dvaas/dataplane_validation.cc
- dvaas/test_run_validation.cc
- dvaas/test_run_validation.h
- dvaas/test_run_validation_test.cc
- dvaas/test_run_validation_test_runner.cc
- dvaas/traffic_generator.cc
- dvaas/validation_result.cc
- dvaas/validation_result.h
Keyword Check:
sk/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/tools/keyword_checks.sh .
Build Result:
INFO: Analyzed 746 targets (267 packages loaded, 22396 targets configured).
INFO: Found 746 targets...
INFO: From Compiling dvaas/arriba_test_vector_validation.cc:
In file included from ./gutil/proto.h:26,
from dvaas/arriba_test_vector_validation.cc:29:
dvaas/arriba_test_vector_validation.cc: In function 'absl::lts_20240116::StatusOr<dvaas::ValidationResult> dvaas::ValidateAgainstArribaTestVector(pdpi::P4RuntimeSession&, pdpi::P4RuntimeSession&, const ArribaTestVector&, const ArribaTestVectorValidationParams&)': …
> [Dvaas] Refactor `ValidateTestRun` and `ValidateTestRuns` to return a `StatusOr`.

- sai_p4/instantiations/google/acl_ingress.p4
- sai_p4/instantiations/google/fabric_border_router.p4info.pb.txt
- sai_p4/instantiations/google/middleblock.p4info.pb.txt
- sai_p4/instantiations/google/test_tools/table_entry_generator.cc
- sai_p4/instantiations/google/test_tools/test_entries.cc
- sai_p4/instantiations/google/test_tools/test_entries.h
- sai_p4/instantiations/google/test_tools/test_entries_test.cc
Enable AppendIngressAndEgressTimestampAction in SAI P4 and Add new AddRouterInterfaceTableEntry function.
bibhuprasad@b53a70426c59:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 744 targets (0 packages loaded, 0 targets configured).
INFO: Found 744 targets...
INFO: Elapsed time: 0.457s, Critical Path: 0.01s
bibhuprasad@b53a70426c59:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 744 targets (0 packages loaded, 0 targets configured).
INFO: Found 517 targets and 227 …
> [SAI_P4] Enable AppendIngressAndEgressTimestampAction in SAI P4 and Add new AddRouterInterfaceTableEntry function.

- tests/integration/system/nsf/BUILD.bazel
- tests/integration/system/nsf/interfaces/BUILD.bazel
- tests/integration/system/nsf/interfaces/traffic_helper.h
- tests/integration/system/nsf/nsf_acl_flow_coverage_test.cc
- tests/integration/system/nsf/nsf_concurrent_config_push_flow_programming_test.cc
- tests/integration/system/nsf/traffic_helpers/BUILD.bazel
- tests/integration/system/nsf/traffic_helpers/otg_helper.cc
- tests/integration/system/nsf/traffic_helpers/otg_helper.h
- tests/integration/system/nsf/upgrade_test.cc
- tests/integration/system/nsf/upgrade_test.h
- tests/integration/system/nsf/util.cc
- tests/integration/system/nsf/util.h
Keyword Check:
Build Result:
INFO: Analyzed 753 targets (0 packages loaded, 0 targets configured).
INFO: Found 753 targets...
INFO: Elapsed time: 0.617s, Critical Path: 0.01s
Test Result:
INFO: Analyzed 750 targets (0 packages loaded, 0 targets configured).
INFO: Found 521 targets and 229 test targets...
INFO: Elapsed time: 279.733s, Critical Path: 143.63s
INFO: Build completed successfully, 286 …
> [Thinkit/Tests] Standardize config artifacts for No Config Push NSF Upgrade scenario.

- sai_p4/instantiations/google/acl_pre_ingress.p4
- sai_p4/instantiations/google/fabric_border_router.p4info.pb.txt
- sai_p4/instantiations/google/sai_pd.proto
- sai_p4/instantiations/google/tor.p4info.pb.txt
- sai_p4/instantiations/google/unioned_p4info.pb.txt
Add action set_outer_vlan_id to acl_pre_ingress_metadata_table.
bibhuprasad@82776d065fcc:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 747 targets (0 packages loaded, 0 targets configured).
INFO: Found 747 targets...
INFO: Elapsed time: 0.384s, Critical Path: 0.00s
bibhuprasad@82776d065fcc:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 747 targets (0 packages loaded, 0 targets configured).
INFO: Found 518 targets and 229 test targets...
INFO: Elapsed time: …
> [SAI_P4] Add action set_outer_vlan_id to acl_pre_ingress_metadata_table.

- tests/forwarding/l3_multicast_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 754 targets (2 packages loaded, 44 targets configured).
INFO: Found 754 targets...
INFO: Elapsed time: 56.239s, Critical Path: 48.42s
INFO: 7 processes: 1 internal, 6 linux-sandbox.
INFO: Build completed successfully, 7 total actions
Test Result:
INFO: Analyzed 754 targets (0 packages loaded, 0 targets configured).
INFO: Found 525 targets and 229 test targets...
INFO: Elapsed time: 273.420s, Critical Path: 150.30s
INFO: Build …
> [Thinkit/Tests] Add test case to confirm replication to same port is successful.

- p4_pdpi/packetlib/packetlib_unit_test.cc
Add Update All Computed Fields Has NonZero Padding For NPadding test to packetlib.
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 753 targets (0 packages loaded, 0 targets configured).
INFO: Found 753 targets...
INFO: Elapsed time: 0.442s, Critical Path: 0.01s
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 753 targets (0 packages loaded, 74 targets configured).
INFO: Found 524 targets and 229 test targets...
INFO: …
> [Comb] Add Update All Computed Fields Has NonZero Padding For NPadding test to packetlib.

- tests/forwarding/l3_multicast_test.cc
- tests/integration/system/nsf/component_validators/BUILD.bazel
- tests/integration/system/nsf/component_validators/telemetry_validator.cc
- tests/integration/system/nsf/component_validators/telemetry_validator.h
Keyword Check:
Build Result:
INFO: Analyzed 752 targets (269 packages loaded, 22408 targets configured).
INFO: Found 752 targets...
INFO: Elapsed time: 261.867s, Critical Path: 53.66s
INFO: 84 processes: 17 internal, 67 linux-sandbox.
INFO: Build completed successfully, 84 total actions
Test Result:
INFO: Analyzed 752 targets (0 packages loaded, 383 targets configured).
INFO: Found 523 targets and 229 test targets...
INFO: Elapsed time: 308.734s, Critical Path: 157.69s …
> [Thinkit/Tests] Add telemetry validator for NSF.

- tests/forwarding/tunnel_decap_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 755 targets (0 packages loaded, 0 targets configured).
INFO: Found 755 targets...
INFO: Elapsed time: 31.156s, Critical Path: 30.31s
Test Result:
INFO: Analyzed 755 targets (0 packages loaded, 0 targets configured).
INFO: Found 526 targets and 229 test targets...
INFO: Elapsed time: 254.455s, Critical Path: 147.98s
INFO: Build …
> [Thinkit/tests] Adding Helper function to build a Ipv4 in Ipv6 packet

- tests/forwarding/tunnel_decap_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 757 targets (0 packages loaded, 0 targets configured).
INFO: Found 757 targets...
INFO: Elapsed time: 32.158s, Critical Path: 30.31s
Test Result:
INFO: Analyzed 755 targets (0 packages loaded, 0 targets configured).
INFO: Found 526 targets and 229 test targets...
INFO: Elapsed time: 254.455s, Critical Path: 147.98s
INFO: Build …
> [Thinkit/tests] Adding Helper routine to install ingress acl redirect to egress port

- p4_pdpi/packetlib/packetlib_unit_test.cc
Add Mld Packet tests to packetlib.
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 753 targets (0 packages loaded, 0 targets configured).
INFO: Found 753 targets...
INFO: Elapsed time: 0.434s, Critical Path: 0.00s
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 753 targets (0 packages loaded, 0 targets configured).
INFO: Found 524 targets and 229 test targets...
INFO: Elapsed time: 193.036s, Critical Path: 135.65s …
> [Comb] Add Mld Packet tests to packetlib.

- p4_pdpi/packetlib/packetlib_unit_test.cc
- p4_symbolic/tests/sai_p4_integration_test.cc
- sai_p4/instantiations/google/test_tools/table_entry_generator.cc
- sai_p4/instantiations/google/test_tools/test_entries.cc
- sai_p4/instantiations/google/test_tools/test_entries.h
- sai_p4/instantiations/google/test_tools/test_entries_test.cc
- tests/qos/frontpanel_qos_test.cc
Remove use of old multicast action in tests.
bibhuprasad@0c2403497cee:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 756 targets (0 packages loaded, 0 targets configured).
INFO: Found 756 targets...
INFO: Elapsed time: 0.447s, Critical Path: 0.00s
bibhuprasad@0c2403497cee:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 756 targets (0 packages loaded, 2 targets configured).
INFO: Found 526 targets and 230 test targets...
INFO: Elapsed time: 196.812s, Critical Path: …
> [Comb] Remove use of old multicast action in tests.

- sai_p4/tools/BUILD.bazel
- sai_p4/tools/auxiliary_entries_for_v1model_targets.cc
- sai_p4/tools/auxiliary_entries_for_v1model_targets.h
- sai_p4/tools/auxiliary_entries_for_v1model_targets_test.cc
Add auxiliary entries for v1model_auxiliary_vlan_membership_table given switch table entries.
bibhuprasad@0c2403497cee:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 756 targets (0 packages loaded, 0 targets configured).
INFO: Found 756 targets...
INFO: Elapsed time: 0.468s, Critical Path: 0.00s
bibhuprasad@8b3c841bfe91:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 754 targets (0 packages loaded, 0 targets configured).
INFO: Found 525 targets and 229 test …
> [Comb] Add auxiliary entries for v1model_auxiliary_vlan_membership_table given switch table entries.

- p4_pdpi/ir.proto
- p4_pdpi/packetlib/packetlib.cc
- p4_pdpi/references.cc
- sai_p4/instantiations/google/acl_egress.p4
- sai_p4/instantiations/google/ids.h
- sai_p4/instantiations/google/middleblock.p4info.pb.txt
- sai_p4/instantiations/google/sai_pd.proto
- sai_p4/instantiations/google/tor.p4info.pb.txt
- sai_p4/instantiations/google/unioned_p4info.pb.txt
Fix ICMP checksum calculator by updating the next_header field and Remove unused L2 table from ACL egress pipeline. 
Keyword Check:
bibhuprasad@bibhuprasad87:~/sonic_build_image_2025-06-23/sonic-buildimage/src/sonic-p4rt/sonic-pins/p4_pdpi$ sh ~/keyword_check.sh .
Build Results:
bibhuprasad@8b3c841bfe91:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 754 targets (0 packages loaded, 0 targets configured).
INFO: Found 754 targets...
INFO: Elapsed time: 0.455s, Critical Path: 0.01s
UT Results:
bibhuprasad@8b3c841bfe91:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 754 targets (0 …
> [Comb] Fix ICMP checksum calculator by updating the next_header field and Remove unused L2 table from ACL egress pipeline.

- tests/gnmi/blackhole_congestion_counters_without_ixia_test.cc
- tests/gnmi/blackhole_congestion_counters_without_ixia_test.h
Keyword Check:
Build Result:
INFO: Analyzed 755 targets (0 packages loaded, 0 targets configured).
INFO: Found 755 targets...
INFO: Elapsed time: 31.156s, Critical Path: 30.31s
Test Result:
INFO: Analyzed 755 targets (0 packages loaded, 0 targets configured).
INFO: Found 526 targets and 229 test targets...
INFO: Elapsed time: 254.455s, Critical Path: 147.98s
INFO: Build …
> [Thinkit/Tests] Add test cases for non-congestion related out discards.

- gutil/overload.h
- lib/BUILD.bazel
- lib/ixia_helper.cc
- lib/ixia_helper.h
- lib/ixia_helper_test.cc
- lib/lacp_ixia_helper.cc
- lib/lacp_ixia_helper.h
Add wrapper to simplify LACP traffic item creation and utilities.
bibhuprasad@bibhuprasad87:~/sonic_build_image_2025-08-20/sonic-buildimage/src/sonic-p4rt/sonic-pins/p4_pdpi$ sh ~/keyword_check.sh .
bibhuprasad@8b3c841bfe91:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 759 targets (0 packages loaded, 0 targets configured).
INFO: Found 759 targets...
INFO: Elapsed time: 0.546s, Critical Path: 0.01s
bibhuprasad@8b3c841bfe91:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 759 targets (0 packages loaded, 384 targets configured).
INFO: Found 529 targets and 230 test targets...
INFO: Elapsed time: …
> [Comb] Add wrapper to simplify LACP traffic item creation and utilities.

- tests/integration/system/nsf/BUILD.bazel
- tests/integration/system/nsf/upgrade_test.cc
- tests/integration/system/nsf/upgrade_test.h
Keyword Check:
Build Result:
INFO: Analyzed 754 targets (1 packages loaded, 27 targets configured).
INFO: Found 754 targets...
INFO: Elapsed time: 42.241s, Critical Path: 41.11s
Test Result:
INFO: Analyzed 754 targets (0 packages loaded, 0 targets configured).
INFO: Found 525 targets and 229 test targets...
INFO: Elapsed time: 287.463s, Critical Path: 142.72s
INFO: Build …
> [Thinkit/Tests] Validate traffic and ACL flows across NSF upgrade using snapshot comparisons.

- tests/forwarding/BUILD.bazel
- tests/forwarding/watch_port_test.cc
- tests/integration/system/nsf/traffic_helpers/otg_helper.cc
- tests/integration/system/nsf/upgrade_test.cc
- tests/qos/frontpanel_qos_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 756 targets (2 packages loaded, 42 targets configured).
INFO: Found 756 targets...
INFO: From Compiling tests/integration/system/nsf/nsf_acl_flow_coverage_test.cc:
tests/integration/system/nsf/nsf_acl_flow_coverage_test.cc: In member function 'virtual void pins_test::NsfAclFlowCoverageTestFixture_NsfAclFlowCoverageTest_Test::TestBody()':
tests/integration/system/nsf/nsf_acl_flow_coverage_test.cc:52:29: warning: unused variable 'environment' [-Wunused-variable]
52 |   thinkit::TestEnvironment &environment = GetTestEnvironment(testbed_);
| …
> [Thinkit/Tests] Update the OTG config related to TCP header and flow rate
