- p4rt_app/sonic/adapters/db_connector_adapter.cc
- p4rt_app/sonic/adapters/db_connector_adapter.h
- p4rt_app/sonic/adapters/fake_db_connector_adapter.cc
- p4rt_app/sonic/adapters/fake_db_connector_adapter.h
- p4rt_app/sonic/adapters/fake_producer_state_table_adapter.cc
- p4rt_app/sonic/adapters/fake_producer_state_table_adapter.h
- p4rt_app/sonic/adapters/mock_db_connector_adapter.h
- p4rt_app/sonic/adapters/mock_producer_state_table_adapter.h
- p4rt_app/sonic/adapters/producer_state_table_adapter.cc
- p4rt_app/sonic/adapters/producer_state_table_adapter.h
- p4rt_app/sonic/app_db_manager.cc
- p4rt_app/sonic/app_db_manager_test.cc
- pins_infra_deps.bzl
HLD: https://github.com/Azure/SONiC/pull/959
> Use batching API to send requests to the AppDb tables.

- p4_pdpi/p4_runtime_session.cc
- p4_pdpi/p4_runtime_session.h
- p4rt_app/scripts/BUILD.bazel
- p4rt_app/scripts/p4rt_route_measurement_test.cc
- p4rt_app/scripts/p4rt_write.cc
- p4rt_app/tests/forwarding_pipeline_config_test.cc
Remove Stub() interface from P4Runtime Session
> Remove Stub() interface from P4Runtime Session

- p4rt_app/sonic/adapters/BUILD.bazel
- p4rt_app/sonic/adapters/mock_notification_producer_adapter.h
- p4rt_app/sonic/adapters/notification_producer_adapter.cc
- p4rt_app/sonic/adapters/notification_producer_adapter.h
**### Build Results:**
divya@6752ad75083d:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS p4_pdpi/...
INFO: Analyzed 70 targets (0 packages loaded, 0 targets configured).
INFO: Found 70 targets...
INFO: Elapsed time: 0.258s, Critical Path: 0.00s
divya@6752ad75083d:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS p4rt_app/...
INFO: Analyzed 94 targets (0 packages loaded, 0 targets configured).
INFO: Found 94 targets...
INFO: Elapsed time: 0.271s, Critical Path: 0.00s
divya@6752ad75083d:/sonic/src/sonic-p4rt/sonic-pins$ 
**### Test Results:**
divya@6752ad75083d:/sonic/src/sonic-p4rt/sonic-pins$ bazel …
> Add NotificationProducer adapter

- p4rt_app/p4rt.cc
- p4rt_app/p4runtime/p4runtime_impl.cc
- p4rt_app/p4runtime/p4runtime_impl.h
- p4rt_app/sonic/BUILD.bazel
- p4rt_app/sonic/redis_connections.h
- p4rt_app/tests/BUILD.bazel
- p4rt_app/tests/grpc_behavior_test.cc
- p4rt_app/tests/lib/p4runtime_grpc_service.cc
- p4rt_app/tests/lib/p4runtime_grpc_service.h
- p4rt_app/tests/state_verification_test.cc
**Build Results:**
=========
divya@ec2dfc05eb3c:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS p4rt_app/...
INFO: Analyzed 93 targets (0 packages loaded, 0 targets configured).
INFO: Found 93 targets...
INFO: Elapsed time: 0.269s, Critical Path: 0.00s
divya@ec2dfc05eb3c:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS p4_pdpi/...
INFO: Analyzed 70 targets (0 packages loaded, 0 targets configured).
INFO: Found 70 targets...
INFO: Elapsed time: 0.280s, Critical Path: 0.01s
**Tests Results:**
=========
divya@ec2dfc05eb3c:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS p4rt_app/...
INFO: …
> Add state verification logic to P4RT App

- p4_pdpi/sequencing_util.cc
- p4_pdpi/sequencing_util.h
- p4_pdpi/testing/BUILD.bazel
- p4_pdpi/testing/sequencing_util_test_runner.cc
- p4_pdpi/testing/testdata/sequencing_util.expected
PR Description :
[P4 Reachability analysis] Define ReferenceRelation and make a helper function to create them out of P4Info.
Build Results :
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 257 targets (0 packages loaded, 0 targets configured).
INFO: Found 257 targets...
INFO: Elapsed time: 22.723s, Critical Path: 14.24s
INFO: 10 processes: 3 internal, 7 linux-sandbox.
INFO: Build completed successfully, 10 total actions
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ 
UT Results :
bibhuprasad@26c7ccef2fda:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS p4_pdpi/...
INFO: Analyzed 84 targets (0 packages loaded, 0 targets configured).
INFO: Found 48 targets and 36 test targets...
INFO: Elapsed time: …
> [P4 Reachability analysis] Define ReferenceRelation and make a helper function to create them out of P4Info.

- p4rt_app/p4runtime/p4info_verification.cc
Add ACL verification.
Keyword check:
Build Results:
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analyzed 281 targets (1 packages loaded, 17436 targets configured).
INFO: Found 281 targets...
INFO: Elapsed time: 32.814s, Critical Path: 25.34s
INFO: 34 processes: 3 internal, 31 linux-sandbox.
INFO: Build completed successfully, 34 total actions
UT Results:
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS …
> Add ACL verification.

- p4_pdpi/BUILD.bazel
- p4_pdpi/ir.cc
- p4_pdpi/ir.h
- p4_pdpi/ir.proto
- p4_pdpi/pd.cc
- p4_pdpi/pd.h
- p4_pdpi/pdgen.cc
- p4_pdpi/pdgenlib.cc
- p4_pdpi/pdgenlib.h
- p4_pdpi/testing/table_entry_gunit_test.cc
- p4_pdpi/testing/table_entry_test_runner.cc
- p4_pdpi/testing/testdata/main_p4_pd.expected
- p4_pdpi/testing/testdata/table_entry.expected
- sai_p4/instantiations/google/sai_pd.proto
[pd][multicast] Add MulticastGroupTableEntry to sai_pd.proto.
Keyword Check:
Build Results:
INFO: Analyzed 284 targets (0 packages loaded, 0 targets configured).
INFO: Found 284 targets...
INFO: Elapsed time: 0.748s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 284 targets (0 packages loaded, 76 …
> [Comb][multicast] Add MulticastGroupTableEntry to sai_pd.proto.

- p4_pdpi/testing/testdata/info.expected
- p4_pdpi/testing/testdata/main.p4
- p4_pdpi/testing/testdata/main_p4_pd.expected
[pdpi] Introduce tables with only print friendly formats for golden testing.
Keyword Check:
Build Results:
INFO: Analyzed 311 targets (0 packages loaded, 0 targets configured).
INFO: Found 311 targets...
INFO: Elapsed time: 0.775s, Critical Path: 0.00s
UT Results:
INFO: Analyzed 311 targets (0 packages …
> [Comb] Introduce tables with only print friendly formats for golden testing.

- bazel/patches/gnmi-001-fix_virtual_proto_import.patch
- lib/BUILD.bazel
- lib/basic_switch.h
- lib/gnmi/BUILD.bazel
- lib/gnmi/openconfig.proto
- pins_infra_deps.bzl
- tests/lib/switch_test_setup_helpers.cc
Adding basic_switch.h to lib
Keyword Check:
Build Results:
INFO: Analyzed 323 targets (26 packages loaded, 415 targets configured).
INFO: Found 323 targets...
INFO: Elapsed time: 5.176s, Critical Path: 0.02s
bibhuprasad@bb37b62b1ae4:/sonic/src/sonic-p4rt/sonic-pins$
UT Results:
INFO: Analyzed 323 targets (0 packages loaded, 271 targets configured).
INFO: Found …
> [Thinkit]Adding basic_switch.h to lib.

- gutil/BUILD.bazel
- gutil/proto_ordering.cc
- gutil/proto_ordering.h
- gutil/proto_ordering_test.cc
- sai_p4/instantiations/google/test_tools/BUILD.bazel
- sai_p4/instantiations/google/test_tools/test_entries.cc
INFO: Analyzed 339 targets (239 packages loaded, 19714 targets configured).
INFO: Found 339 targets...
...
INFO: Elapsed time: 181.489s, Critical Path: 67.66s
INFO: 268 processes: 132 internal, 136 linux-sandbox.
INFO: Build completed successfully, 268 total actions
INFO: Analyzed 339 targets (0 packages loaded, 271 targets configured).
INFO: Found 222 targets and 117 test targets...
INFO: Elapsed time: 64.925s, Critical Path: 16.51s
INFO: 122 processes: 129 linux-sandbox, 17 local.
INFO: Build completed successfully, 122 total actions …
> [gutil] Add functions for proto ordering, sorting, deduping.

- pins_infra_deps.bzl
- tests/thinkit_sanity_tests.cc
- tests/thinkit_sanity_tests.h
INFO: Analyzed 348 targets (1 packages loaded, 7 targets configured).
INFO: Found 348 targets...
INFO: Elapsed time: 8.477s, Critical Path: 7.92s
INFO: Analyzed 348 targets (0 packages loaded, 275 targets configured).
INFO: Found 227 targets and 121 test targets...
INFO: Elapsed time: 68.622s, Critical Path: 22.32s
INFO: 126 processes: 133 linux-sandbox, 17 local.
INFO: Build …
> [Thinkit] gnmi sanity tests &  gnmi interface state tests.

- lib/utils/json_utils.cc
- lib/utils/json_utils_test.cc
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
...
INFO: Elapsed time: 16.013s, Critical Path: 15.55s
INFO: Analyzed 382 targets (0 packages loaded, 0 targets configured).
INFO: Elapsed time: 62.326s, Critical Path: 16.62s
INFO: Build …
> [Thinkit] FlattenJsonToMap() will now return all leaf paths that are absent in the input map.

- lib/gnmi/openconfig.proto
- thinkit/mirror_testbed_fixture.h
divya@cfdc38a2acd6:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
...
INFO: Elapsed time: 185.739s, Critical Path: 42.50s
INFO: 114 processes: 13 internal, 101 linux-sandbox.
INFO: Build completed successfully, 114 total actions
divya@cfdc38a2acd6:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Elapsed time: 89.343s, Critical Path: …
> [Comb] Update FuzzTest to thinkit::MirrorTestbed & For buffer profile, update qos subtree including qos-interfaces.

- p4_pdpi/BUILD.bazel
- p4_pdpi/built_ins.cc
- p4_pdpi/built_ins.h
- p4_pdpi/helpers.cc
- p4_pdpi/helpers.h
- p4_pdpi/helpers_test.cc
- p4_pdpi/ir.proto
- p4_pdpi/sequencing.cc
- p4_pdpi/sequencing.h
- p4_pdpi/testing/sequencing_test_runner.cc
- p4_pdpi/testing/testdata/sequencing.expected
/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ./key.sh p4_pdpi/
/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS  ...
INFO: Analyzed 394 targets (0 packages loaded, 0 targets configured).
INFO: Found 394 targets...
INFO: From Compiling p4_pdpi/sequencing.cc:
In file included from external/boost/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
from external/boost/boost/smart_ptr/detail/yield_k.hpp:23,
from external/boost/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
from external/boost/boost/smart_ptr/detail/spinlock.hpp:42,
from external/boost/boost/smart_ptr/detail/spinlock_pool.hpp:25,
INFO: From Compiling p4_pdpi/testing/sequencing_test_runner.cc:
p4_pdpi/testing/sequencing_test_runner.cc:1000:3: warning: multi-line comment [-Wcomment]
1000 |   // …
> [PDPI] : Add SortEntities to sequencing.

- p4_symbolic/bmv2/bmv2.cc
- p4_symbolic/bmv2/bmv2.h
- p4_symbolic/bmv2/bmv2.proto
sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/Tools/keyword_checks.sh .
INFO: Analyzed 411 targets (244 packages loaded, 19887 targets configured).
INFO: Found 411 targets...
INFO: Elapsed time: 370.699s, Critical Path: 35.40s
INFO: Analyzed 411 targets (0 packages loaded, 302 targets configured).
INFO: Found 263 targets and 148 test targets...
INFO: Elapsed time: 177.053s, Critical Path: 26.22s
INFO: 153 processes: 163 linux-sandbox, 18 local.
INFO: Build completed successfully, …
> [P4-Symbolic] Modified p4_symbolic/bmv2/bmv2.cc, bmv2.h, bmv2.proto files

- tests/qos/BUILD.bazel
- tests/qos/cpu_qos_test.cc
- tests/qos/cpu_qos_test.h
sdivya@eonms6vm1:~/sonic_sep6/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh .
sdivya@5b4a22f9835d:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1619053724 -0700"
DEBUG: Repository com_github_nelhage_rules_boost instantiated at:
/sonic/src/sonic-p4rt/sonic-pins/WORKSPACE.bazel:128:9: in <toplevel>
/var/sdivya/.cache/bazel/_bazel_sdivya/5fd88bad78ef03829a4685c83637a020/external/com_github_p4lang_p4c/bazel/p4c_deps.bzl:25:23: in p4c_deps
Repository rule git_repository defined at:
/var/sdivya/.cache/bazel/_bazel_sdivya/5fd88bad78ef03829a4685c83637a020/external/bazel_t …
> [Thinkit] CPU QoS test.

- pins_infra_deps.bzl
- tests/integration/system/alpm_miss_counter_tests.cc
- tests/integration/system/nsf/interfaces/BUILD.bazel
- tests/integration/system/nsf/interfaces/component_validator.h
- tests/integration/system/nsf/interfaces/flow_programmer.h
- tests/integration/system/nsf/interfaces/test_params.h
- tests/integration/system/nsf/interfaces/traffic_helper.h
- tests/integration/system/nsf/traffic_helpers/BUILD.bazel
- tests/integration/system/nsf/traffic_helpers/dvaas_helper.h
- tests/integration/system/nsf/traffic_helpers/otg_helper.h
Key_word Check:
```
~/pins_upstream/sonic-buildimage/src/sonic-p4rt/sonic-pins/tests/sflow$ ~/tools/keyword_checks.sh .
```
Build result:
```
INFO: Analyzed 671 targets (27 packages loaded, 1452 targets configured).
INFO: Found 671 targets...
INFO: Elapsed time: 2.521s, Critical Path: 0.04s
```
Test result:
```
INFO: Analyzed 673 targets (0 packages loaded, 372 targets configured).
INFO: Found 456 targets and 217 test targets...
INFO: Elapsed time: 165.434s, Critical Path: 119.58s
INFO: 270 processes: 326 linux-sandbox, 18 local. …
```
> [Thinkit] Create interfaces, structs, and enums to be used in PINs NSF tests.Implement the various traffic generator helpers for PINs NSF tests.

- tests/qos/frontpanel_qos_test.cc
- tests/qos/frontpanel_qos_test.h
divyagayathris@divyagayathris-16:~/Dec_23/sonic-buildimage/src/sonic-p4rt/sonic-pins$ ~/keyword_check.sh tests/.
divyagayathris@25f33459dcdc:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 675 targets (0 packages loaded, 0 targets configured).
INFO: Found 675 targets...
INFO: Elapsed time: 171.436s, Critical Path: 109.05s
INFO: 1088 processes: 162 internal, 926 linux-sandbox.
INFO: Build completed successfully, 1088 total actions
divyagayathris@25f33459dcdc:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 675 targets (0 packages loaded, 372 targets configured).
INFO: Found 459 targets and 216 test targets...
INFO: Elapsed time: 169.007s, Critical Path: 121.20s
INFO: 270 …
> [Comb] Add provision to pass in ingress and egress ports to tests.

- sai_p4/instantiations/google/fabric_border_router.p4info.pb.txt
- sai_p4/instantiations/google/middleblock.p4info.pb.txt
- sai_p4/instantiations/google/tor.p4info.pb.txt
- sai_p4/instantiations/google/unioned_p4info.pb.txt
- sai_p4/instantiations/google/versions.h
- sai_p4/instantiations/google/wbb.p4info.pb.txt
Add new version indicating that `acl_ingress_table` modification is supported.
bibhuprasad@b53a70426c59:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 744 targets (0 packages loaded, 0 targets configured).
INFO: Found 744 targets...
INFO: Elapsed time: 0.294s, Critical Path: 0.00s
bibhuprasad@b53a70426c59:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 744 targets (0 packages loaded, 381 targets configured).
INFO: Found 517 targets and 227 test targets...
INFO: …
> [SAI_P4] Add new version indicating that `acl_ingress_table` modification is supported.

- tests/forwarding/tunnel_decap_test.cc
Keyword Check:
Build Result:
2025/08/21 07:08:55 Downloading https://releases.bazel.build/6.4.0/release/bazel-6.4.0-linux-x86_64...
Downloading: 52 MB out of 52 MB (100%) 
Extracting Bazel installation...
DEBUG: Rule 'sonic_swss_common' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "179a18c55c696c2ea9ed3f015e7e24133f61416a33cad1a2650eaa300510f339"
DEBUG: Repository sonic_swss_common instantiated at:
/sonic/src/sonic-p4rt/sonic-pins/WORKSPACE.bazel:42:16: in <toplevel> …
> [Thinkit/Tests] Add IPV4-in-IPV6 tunnel termination tests and logging enhancements.

- p4_pdpi/packetlib/packetlib_unit_test.cc
Add Update Computed Fields Adds SinglePadding For NPadding For HopByHop Options tests to packetlib
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel build $BAZEL_BUILD_OPTS ...
INFO: Analyzed 753 targets (0 packages loaded, 0 targets configured).
INFO: Found 753 targets...
INFO: Elapsed time: 0.467s, Critical Path: 0.00s
bibhuprasad@cc8b5015ed50:/sonic/src/sonic-p4rt/sonic-pins$ bazel test $BAZEL_BUILD_OPTS --cache_test_results=no ...
INFO: Analyzed 753 targets (0 packages loaded, 383 targets configured).
INFO: Found 524 targets and 229 test …
> [Comb] Add Update Computed Fields Adds SinglePadding For NPadding For HopByHop Options tests to packetlib.

- tests/forwarding/acl_feature_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 752 targets (0 packages loaded, 0 targets configured).
INFO: Found 752 targets...
INFO: Elapsed time: 0.936s, Critical Path: 0.00s
Test Result:
INFO: Analyzed 752 targets (0 packages loaded, 0 targets configured).
INFO: Found 523 targets and 229 test targets...
INFO: Elapsed time: 218.220s, Critical Path: 145.06s
INFO: Build completed successfully, 286 …
> [Thinkit/Tests] Add tests for ACL Egress table L2 matches.

- tests/qos/cpu_qos_test.cc
Keyword Check:
Build Result:
INFO: Analyzed 754 targets (6 packages loaded, 133 targets configured).
INFO: Found 754 targets...
INFO: Elapsed time: 108.109s, Critical Path: 41.27s
INFO: 53 processes: 2 internal, 51 linux-sandbox.
INFO: Build completed successfully, 53 total actions
Test Result:
INFO: Analyzed 754 targets (0 packages loaded, 5 targets configured).
INFO: Found 525 targets and 229 test targets...
INFO: Elapsed time: 259.200s, Critical Path: 149.74s
INFO: Build …
> [Thinkit/Tests] Add coverage to verify set_cpu_queue action in ACL QoS table
